/*
 * This file is generated by jOOQ.
 */
package com.merchant.pipe.db.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * actionPipe
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProcessActionPipe implements Serializable {

    private static final long serialVersionUID = 1580806833;

    private Long          id;
    private String        name;
    private Long          taskId;
    private Long          processId;
    private String        context;
    private String        status;
    private String        headStageNo;
    private String        tailStageNo;
    private LocalDateTime triggerTime;
    private LocalDateTime doneTime;
    private LocalDateTime ctime;
    private LocalDateTime mtime;
    private String        pipeOrganizer;
    private Integer       pipeType;

    public ProcessActionPipe() {}

    public ProcessActionPipe(ProcessActionPipe value) {
        this.id = value.id;
        this.name = value.name;
        this.taskId = value.taskId;
        this.processId = value.processId;
        this.context = value.context;
        this.status = value.status;
        this.headStageNo = value.headStageNo;
        this.tailStageNo = value.tailStageNo;
        this.triggerTime = value.triggerTime;
        this.doneTime = value.doneTime;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
        this.pipeOrganizer = value.pipeOrganizer;
        this.pipeType = value.pipeType;
    }

    public ProcessActionPipe(
        Long          id,
        String        name,
        Long          taskId,
        Long          processId,
        String        context,
        String        status,
        String        headStageNo,
        String        tailStageNo,
        LocalDateTime triggerTime,
        LocalDateTime doneTime,
        LocalDateTime ctime,
        LocalDateTime mtime,
        String        pipeOrganizer,
        Integer       pipeType
    ) {
        this.id = id;
        this.name = name;
        this.taskId = taskId;
        this.processId = processId;
        this.context = context;
        this.status = status;
        this.headStageNo = headStageNo;
        this.tailStageNo = tailStageNo;
        this.triggerTime = triggerTime;
        this.doneTime = doneTime;
        this.ctime = ctime;
        this.mtime = mtime;
        this.pipeOrganizer = pipeOrganizer;
        this.pipeType = pipeType;
    }

    public Long getId() {
        return this.id;
    }

    public ProcessActionPipe setId(Long id) {
        this.id = id;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public ProcessActionPipe setName(String name) {
        this.name = name;
        return this;
    }

    public Long getTaskId() {
        return this.taskId;
    }

    public ProcessActionPipe setTaskId(Long taskId) {
        this.taskId = taskId;
        return this;
    }

    public Long getProcessId() {
        return this.processId;
    }

    public ProcessActionPipe setProcessId(Long processId) {
        this.processId = processId;
        return this;
    }

    public String getContext() {
        return this.context;
    }

    public ProcessActionPipe setContext(String context) {
        this.context = context;
        return this;
    }

    public String getStatus() {
        return this.status;
    }

    public ProcessActionPipe setStatus(String status) {
        this.status = status;
        return this;
    }

    public String getHeadStageNo() {
        return this.headStageNo;
    }

    public ProcessActionPipe setHeadStageNo(String headStageNo) {
        this.headStageNo = headStageNo;
        return this;
    }

    public String getTailStageNo() {
        return this.tailStageNo;
    }

    public ProcessActionPipe setTailStageNo(String tailStageNo) {
        this.tailStageNo = tailStageNo;
        return this;
    }

    public LocalDateTime getTriggerTime() {
        return this.triggerTime;
    }

    public ProcessActionPipe setTriggerTime(LocalDateTime triggerTime) {
        this.triggerTime = triggerTime;
        return this;
    }

    public LocalDateTime getDoneTime() {
        return this.doneTime;
    }

    public ProcessActionPipe setDoneTime(LocalDateTime doneTime) {
        this.doneTime = doneTime;
        return this;
    }

    public LocalDateTime getCtime() {
        return this.ctime;
    }

    public ProcessActionPipe setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
        return this;
    }

    public LocalDateTime getMtime() {
        return this.mtime;
    }

    public ProcessActionPipe setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
        return this;
    }

    public String getPipeOrganizer() {
        return this.pipeOrganizer;
    }

    public ProcessActionPipe setPipeOrganizer(String pipeOrganizer) {
        this.pipeOrganizer = pipeOrganizer;
        return this;
    }

    public Integer getPipeType() {
        return this.pipeType;
    }

    public ProcessActionPipe setPipeType(Integer pipeType) {
        this.pipeType = pipeType;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProcessActionPipe (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(taskId);
        sb.append(", ").append(processId);
        sb.append(", ").append(context);
        sb.append(", ").append(status);
        sb.append(", ").append(headStageNo);
        sb.append(", ").append(tailStageNo);
        sb.append(", ").append(triggerTime);
        sb.append(", ").append(doneTime);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);
        sb.append(", ").append(pipeOrganizer);
        sb.append(", ").append(pipeType);

        sb.append(")");
        return sb.toString();
    }
}
