/*
 * This file is generated by jOOQ.
 */
package com.merchant.pipe.db.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * process_action
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProcessAction implements Serializable {

    private static final long serialVersionUID = 1482645086;

    private Long          id;
    private String        itemNo;
    private Long          pipeId;
    private String        stageNo;
    private String        name;
    private String        context;
    private String        inputScript;
    private String        clazz;
    private String        param;
    private String        result;
    private String        bizExplain;
    private Integer       execCount;
    private String        errMsg;
    private String        tip;
    private Long          taskId;
    private String        taskCode;
    private Long          processId;
    private String        status;
    private String        execMode;
    private String        ucid;
    private String        adminAccounts;
    private LocalDateTime doneTime;
    private LocalDateTime ctime;
    private LocalDateTime mtime;
    private Integer       deleted;

    public ProcessAction() {}

    public ProcessAction(ProcessAction value) {
        this.id = value.id;
        this.itemNo = value.itemNo;
        this.pipeId = value.pipeId;
        this.stageNo = value.stageNo;
        this.name = value.name;
        this.context = value.context;
        this.inputScript = value.inputScript;
        this.clazz = value.clazz;
        this.param = value.param;
        this.result = value.result;
        this.bizExplain = value.bizExplain;
        this.execCount = value.execCount;
        this.errMsg = value.errMsg;
        this.tip = value.tip;
        this.taskId = value.taskId;
        this.taskCode = value.taskCode;
        this.processId = value.processId;
        this.status = value.status;
        this.execMode = value.execMode;
        this.ucid = value.ucid;
        this.adminAccounts = value.adminAccounts;
        this.doneTime = value.doneTime;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
        this.deleted = value.deleted;
    }

    public ProcessAction(
        Long          id,
        String        itemNo,
        Long          pipeId,
        String        stageNo,
        String        name,
        String        context,
        String        inputScript,
        String        clazz,
        String        param,
        String        result,
        String        bizExplain,
        Integer       execCount,
        String        errMsg,
        String        tip,
        Long          taskId,
        String        taskCode,
        Long          processId,
        String        status,
        String        execMode,
        String        ucid,
        String        adminAccounts,
        LocalDateTime doneTime,
        LocalDateTime ctime,
        LocalDateTime mtime,
        Integer       deleted
    ) {
        this.id = id;
        this.itemNo = itemNo;
        this.pipeId = pipeId;
        this.stageNo = stageNo;
        this.name = name;
        this.context = context;
        this.inputScript = inputScript;
        this.clazz = clazz;
        this.param = param;
        this.result = result;
        this.bizExplain = bizExplain;
        this.execCount = execCount;
        this.errMsg = errMsg;
        this.tip = tip;
        this.taskId = taskId;
        this.taskCode = taskCode;
        this.processId = processId;
        this.status = status;
        this.execMode = execMode;
        this.ucid = ucid;
        this.adminAccounts = adminAccounts;
        this.doneTime = doneTime;
        this.ctime = ctime;
        this.mtime = mtime;
        this.deleted = deleted;
    }

    public Long getId() {
        return this.id;
    }

    public ProcessAction setId(Long id) {
        this.id = id;
        return this;
    }

    public String getItemNo() {
        return this.itemNo;
    }

    public ProcessAction setItemNo(String itemNo) {
        this.itemNo = itemNo;
        return this;
    }

    public Long getPipeId() {
        return this.pipeId;
    }

    public ProcessAction setPipeId(Long pipeId) {
        this.pipeId = pipeId;
        return this;
    }

    public String getStageNo() {
        return this.stageNo;
    }

    public ProcessAction setStageNo(String stageNo) {
        this.stageNo = stageNo;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public ProcessAction setName(String name) {
        this.name = name;
        return this;
    }

    public String getContext() {
        return this.context;
    }

    public ProcessAction setContext(String context) {
        this.context = context;
        return this;
    }

    public String getInputScript() {
        return this.inputScript;
    }

    public ProcessAction setInputScript(String inputScript) {
        this.inputScript = inputScript;
        return this;
    }

    public String getClazz() {
        return this.clazz;
    }

    public ProcessAction setClazz(String clazz) {
        this.clazz = clazz;
        return this;
    }

    public String getParam() {
        return this.param;
    }

    public ProcessAction setParam(String param) {
        this.param = param;
        return this;
    }

    public String getResult() {
        return this.result;
    }

    public ProcessAction setResult(String result) {
        this.result = result;
        return this;
    }

    public String getBizExplain() {
        return this.bizExplain;
    }

    public ProcessAction setBizExplain(String bizExplain) {
        this.bizExplain = bizExplain;
        return this;
    }

    public Integer getExecCount() {
        return this.execCount;
    }

    public ProcessAction setExecCount(Integer execCount) {
        this.execCount = execCount;
        return this;
    }

    public String getErrMsg() {
        return this.errMsg;
    }

    public ProcessAction setErrMsg(String errMsg) {
        this.errMsg = errMsg;
        return this;
    }

    public String getTip() {
        return this.tip;
    }

    public ProcessAction setTip(String tip) {
        this.tip = tip;
        return this;
    }

    public Long getTaskId() {
        return this.taskId;
    }

    public ProcessAction setTaskId(Long taskId) {
        this.taskId = taskId;
        return this;
    }

    public String getTaskCode() {
        return this.taskCode;
    }

    public ProcessAction setTaskCode(String taskCode) {
        this.taskCode = taskCode;
        return this;
    }

    public Long getProcessId() {
        return this.processId;
    }

    public ProcessAction setProcessId(Long processId) {
        this.processId = processId;
        return this;
    }

    public String getStatus() {
        return this.status;
    }

    public ProcessAction setStatus(String status) {
        this.status = status;
        return this;
    }

    public String getExecMode() {
        return this.execMode;
    }

    public ProcessAction setExecMode(String execMode) {
        this.execMode = execMode;
        return this;
    }

    public String getUcid() {
        return this.ucid;
    }

    public ProcessAction setUcid(String ucid) {
        this.ucid = ucid;
        return this;
    }

    public String getAdminAccounts() {
        return this.adminAccounts;
    }

    public ProcessAction setAdminAccounts(String adminAccounts) {
        this.adminAccounts = adminAccounts;
        return this;
    }

    public LocalDateTime getDoneTime() {
        return this.doneTime;
    }

    public ProcessAction setDoneTime(LocalDateTime doneTime) {
        this.doneTime = doneTime;
        return this;
    }

    public LocalDateTime getCtime() {
        return this.ctime;
    }

    public ProcessAction setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
        return this;
    }

    public LocalDateTime getMtime() {
        return this.mtime;
    }

    public ProcessAction setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
        return this;
    }

    public Integer getDeleted() {
        return this.deleted;
    }

    public ProcessAction setDeleted(Integer deleted) {
        this.deleted = deleted;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProcessAction (");

        sb.append(id);
        sb.append(", ").append(itemNo);
        sb.append(", ").append(pipeId);
        sb.append(", ").append(stageNo);
        sb.append(", ").append(name);
        sb.append(", ").append(context);
        sb.append(", ").append(inputScript);
        sb.append(", ").append(clazz);
        sb.append(", ").append(param);
        sb.append(", ").append(result);
        sb.append(", ").append(bizExplain);
        sb.append(", ").append(execCount);
        sb.append(", ").append(errMsg);
        sb.append(", ").append(tip);
        sb.append(", ").append(taskId);
        sb.append(", ").append(taskCode);
        sb.append(", ").append(processId);
        sb.append(", ").append(status);
        sb.append(", ").append(execMode);
        sb.append(", ").append(ucid);
        sb.append(", ").append(adminAccounts);
        sb.append(", ").append(doneTime);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);
        sb.append(", ").append(deleted);

        sb.append(")");
        return sb.toString();
    }
}
