/*
 * This file is generated by jOOQ.
 */
package com.merchant.kernel.pipe.db.tables;


import com.merchant.kernel.pipe.db.DefaultSchema;
import com.merchant.kernel.pipe.db.Indexes;
import com.merchant.kernel.pipe.db.Keys;
import com.merchant.kernel.pipe.db.tables.records.ProcessActionPipeRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row14;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * actionPipe
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProcessActionPipe extends TableImpl<ProcessActionPipeRecord> {

    private static final long serialVersionUID = 225606417;

    /**
     * The reference instance of <code>process_action_pipe</code>
     */
    public static final ProcessActionPipe PROCESS_ACTION_PIPE = new ProcessActionPipe();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProcessActionPipeRecord> getRecordType() {
        return ProcessActionPipeRecord.class;
    }

    /**
     * The column <code>process_action_pipe.id</code>. pk
     */
    public final TableField<ProcessActionPipeRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "pk");

    /**
     * The column <code>process_action_pipe.name</code>. name
     */
    public final TableField<ProcessActionPipeRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "name");

    /**
     * The column <code>process_action_pipe.task_id</code>. taskId
     */
    public final TableField<ProcessActionPipeRecord, Long> TASK_ID = createField(DSL.name("task_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "taskId");

    /**
     * The column <code>process_action_pipe.process_id</code>. processId
     */
    public final TableField<ProcessActionPipeRecord, Long> PROCESS_ID = createField(DSL.name("process_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "processId");

    /**
     * The column <code>process_action_pipe.context</code>. pipe 上下文
     */
    public final TableField<ProcessActionPipeRecord, String> CONTEXT = createField(DSL.name("context"), org.jooq.impl.SQLDataType.CLOB, this, "pipe 上下文");

    /**
     * The column <code>process_action_pipe.status</code>. status
     */
    public final TableField<ProcessActionPipeRecord, String> STATUS = createField(DSL.name("status"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "status");

    /**
     * The column <code>process_action_pipe.head_stage_no</code>. 头结点 stageNo
     */
    public final TableField<ProcessActionPipeRecord, String> HEAD_STAGE_NO = createField(DSL.name("head_stage_no"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "头结点 stageNo");

    /**
     * The column <code>process_action_pipe.tail_stage_no</code>. 尾节点 stageNo
     */
    public final TableField<ProcessActionPipeRecord, String> TAIL_STAGE_NO = createField(DSL.name("tail_stage_no"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "尾节点 stageNo");

    /**
     * The column <code>process_action_pipe.trigger_time</code>. 定时触发时间
     */
    public final TableField<ProcessActionPipeRecord, LocalDateTime> TRIGGER_TIME = createField(DSL.name("trigger_time"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "定时触发时间");

    /**
     * The column <code>process_action_pipe.done_time</code>. 完成时间
     */
    public final TableField<ProcessActionPipeRecord, LocalDateTime> DONE_TIME = createField(DSL.name("done_time"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.inline("1970-01-02 00:00:00", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "完成时间");

    /**
     * The column <code>process_action_pipe.ctime</code>. ctime
     */
    public final TableField<ProcessActionPipeRecord, LocalDateTime> CTIME = createField(DSL.name("ctime"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "ctime");

    /**
     * The column <code>process_action_pipe.mtime</code>. mtime
     */
    public final TableField<ProcessActionPipeRecord, LocalDateTime> MTIME = createField(DSL.name("mtime"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "mtime");

    /**
     * The column <code>process_action_pipe.pipe_organizer</code>. 主办人
     */
    public final TableField<ProcessActionPipeRecord, String> PIPE_ORGANIZER = createField(DSL.name("pipe_organizer"), org.jooq.impl.SQLDataType.VARCHAR(256).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "主办人");

    /**
     * The column <code>process_action_pipe.pipe_type</code>. 并网类型
     */
    public final TableField<ProcessActionPipeRecord, Integer> PIPE_TYPE = createField(DSL.name("pipe_type"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "并网类型");

    /**
     * Create a <code>process_action_pipe</code> table reference
     */
    public ProcessActionPipe() {
        this(DSL.name("process_action_pipe"), null);
    }

    /**
     * Create an aliased <code>process_action_pipe</code> table reference
     */
    public ProcessActionPipe(String alias) {
        this(DSL.name(alias), PROCESS_ACTION_PIPE);
    }

    /**
     * Create an aliased <code>process_action_pipe</code> table reference
     */
    public ProcessActionPipe(Name alias) {
        this(alias, PROCESS_ACTION_PIPE);
    }

    private ProcessActionPipe(Name alias, Table<ProcessActionPipeRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProcessActionPipe(Name alias, Table<ProcessActionPipeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("actionPipe"), TableOptions.table());
    }

    public <O extends Record> ProcessActionPipe(Table<O> child, ForeignKey<O, ProcessActionPipeRecord> key) {
        super(child, key, PROCESS_ACTION_PIPE);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PROCESS_ACTION_PIPE_PROCESS_ACTION_GROUP_PROCESSID_IDX, Indexes.PROCESS_ACTION_PIPE_PROCESS_ACTION_GROUP_TASKID_IDX);
    }

    @Override
    public Identity<ProcessActionPipeRecord, Long> getIdentity() {
        return Keys.IDENTITY_PROCESS_ACTION_PIPE;
    }

    @Override
    public UniqueKey<ProcessActionPipeRecord> getPrimaryKey() {
        return Keys.KEY_PROCESS_ACTION_PIPE_PRIMARY;
    }

    @Override
    public List<UniqueKey<ProcessActionPipeRecord>> getKeys() {
        return Arrays.<UniqueKey<ProcessActionPipeRecord>>asList(Keys.KEY_PROCESS_ACTION_PIPE_PRIMARY);
    }

    @Override
    public ProcessActionPipe as(String alias) {
        return new ProcessActionPipe(DSL.name(alias), this);
    }

    @Override
    public ProcessActionPipe as(Name alias) {
        return new ProcessActionPipe(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcessActionPipe rename(String name) {
        return new ProcessActionPipe(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcessActionPipe rename(Name name) {
        return new ProcessActionPipe(name, null);
    }

    // -------------------------------------------------------------------------
    // Row14 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row14<Long, String, Long, Long, String, String, String, String, LocalDateTime, LocalDateTime, LocalDateTime, LocalDateTime, String, Integer> fieldsRow() {
        return (Row14) super.fieldsRow();
    }
}
