/*
 * This file is generated by jOOQ.
 */
package com.merchant.pipe.db.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * Action 操作日志表
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProcessActionOpLog implements Serializable {

    private static final long serialVersionUID = 967550571;

    private Long          id;
    private String        resourceNo;
    private String        operationType;
    private LocalDateTime operationTime;
    private String        address;
    private String        username;
    private Long          ucid;
    private LocalDateTime ctime;

    public ProcessActionOpLog() {}

    public ProcessActionOpLog(ProcessActionOpLog value) {
        this.id = value.id;
        this.resourceNo = value.resourceNo;
        this.operationType = value.operationType;
        this.operationTime = value.operationTime;
        this.address = value.address;
        this.username = value.username;
        this.ucid = value.ucid;
        this.ctime = value.ctime;
    }

    public ProcessActionOpLog(
        Long          id,
        String        resourceNo,
        String        operationType,
        LocalDateTime operationTime,
        String        address,
        String        username,
        Long          ucid,
        LocalDateTime ctime
    ) {
        this.id = id;
        this.resourceNo = resourceNo;
        this.operationType = operationType;
        this.operationTime = operationTime;
        this.address = address;
        this.username = username;
        this.ucid = ucid;
        this.ctime = ctime;
    }

    public Long getId() {
        return this.id;
    }

    public ProcessActionOpLog setId(Long id) {
        this.id = id;
        return this;
    }

    public String getResourceNo() {
        return this.resourceNo;
    }

    public ProcessActionOpLog setResourceNo(String resourceNo) {
        this.resourceNo = resourceNo;
        return this;
    }

    public String getOperationType() {
        return this.operationType;
    }

    public ProcessActionOpLog setOperationType(String operationType) {
        this.operationType = operationType;
        return this;
    }

    public LocalDateTime getOperationTime() {
        return this.operationTime;
    }

    public ProcessActionOpLog setOperationTime(LocalDateTime operationTime) {
        this.operationTime = operationTime;
        return this;
    }

    public String getAddress() {
        return this.address;
    }

    public ProcessActionOpLog setAddress(String address) {
        this.address = address;
        return this;
    }

    public String getUsername() {
        return this.username;
    }

    public ProcessActionOpLog setUsername(String username) {
        this.username = username;
        return this;
    }

    public Long getUcid() {
        return this.ucid;
    }

    public ProcessActionOpLog setUcid(Long ucid) {
        this.ucid = ucid;
        return this;
    }

    public LocalDateTime getCtime() {
        return this.ctime;
    }

    public ProcessActionOpLog setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProcessActionOpLog (");

        sb.append(id);
        sb.append(", ").append(resourceNo);
        sb.append(", ").append(operationType);
        sb.append(", ").append(operationTime);
        sb.append(", ").append(address);
        sb.append(", ").append(username);
        sb.append(", ").append(ucid);
        sb.append(", ").append(ctime);

        sb.append(")");
        return sb.toString();
    }
}
