/*
 * This file is generated by jOOQ.
 */
package com.merchant.pipeline.db.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * Pipe 定义表
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProcessActionPipeDef implements Serializable {

    private static final long serialVersionUID = 1737522441;

    private Long          id;
    private String        name;
    private String        code;
    private String        procCode;
    private String        taskCode;
    private String        stageDef;
    private LocalDateTime ctime;
    private LocalDateTime mtime;
    private Integer       deleted;

    public ProcessActionPipeDef() {}

    public ProcessActionPipeDef(ProcessActionPipeDef value) {
        this.id = value.id;
        this.name = value.name;
        this.code = value.code;
        this.procCode = value.procCode;
        this.taskCode = value.taskCode;
        this.stageDef = value.stageDef;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
        this.deleted = value.deleted;
    }

    public ProcessActionPipeDef(
        Long          id,
        String        name,
        String        code,
        String        procCode,
        String        taskCode,
        String        stageDef,
        LocalDateTime ctime,
        LocalDateTime mtime,
        Integer       deleted
    ) {
        this.id = id;
        this.name = name;
        this.code = code;
        this.procCode = procCode;
        this.taskCode = taskCode;
        this.stageDef = stageDef;
        this.ctime = ctime;
        this.mtime = mtime;
        this.deleted = deleted;
    }

    public Long getId() {
        return this.id;
    }

    public ProcessActionPipeDef setId(Long id) {
        this.id = id;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public ProcessActionPipeDef setName(String name) {
        this.name = name;
        return this;
    }

    public String getCode() {
        return this.code;
    }

    public ProcessActionPipeDef setCode(String code) {
        this.code = code;
        return this;
    }

    public String getProcCode() {
        return this.procCode;
    }

    public ProcessActionPipeDef setProcCode(String procCode) {
        this.procCode = procCode;
        return this;
    }

    public String getTaskCode() {
        return this.taskCode;
    }

    public ProcessActionPipeDef setTaskCode(String taskCode) {
        this.taskCode = taskCode;
        return this;
    }

    public String getStageDef() {
        return this.stageDef;
    }

    public ProcessActionPipeDef setStageDef(String stageDef) {
        this.stageDef = stageDef;
        return this;
    }

    public LocalDateTime getCtime() {
        return this.ctime;
    }

    public ProcessActionPipeDef setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
        return this;
    }

    public LocalDateTime getMtime() {
        return this.mtime;
    }

    public ProcessActionPipeDef setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
        return this;
    }

    public Integer getDeleted() {
        return this.deleted;
    }

    public ProcessActionPipeDef setDeleted(Integer deleted) {
        this.deleted = deleted;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProcessActionPipeDef (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(code);
        sb.append(", ").append(procCode);
        sb.append(", ").append(taskCode);
        sb.append(", ").append(stageDef);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);
        sb.append(", ").append(deleted);

        sb.append(")");
        return sb.toString();
    }
}
