/*
 * This file is generated by jOOQ.
 */
package com.merchant.pipeline.db.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * stage 实例表
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProcessActionStage implements Serializable {

    private static final long serialVersionUID = -1877524161;

    private Long          id;
    private Long          pipeId;
    private String        stageNo;
    private String        status;
    private String        nextStageNo;
    private LocalDateTime doneTime;
    private LocalDateTime ctime;
    private LocalDateTime mtime;
    private Integer       deleted;

    public ProcessActionStage() {}

    public ProcessActionStage(ProcessActionStage value) {
        this.id = value.id;
        this.pipeId = value.pipeId;
        this.stageNo = value.stageNo;
        this.status = value.status;
        this.nextStageNo = value.nextStageNo;
        this.doneTime = value.doneTime;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
        this.deleted = value.deleted;
    }

    public ProcessActionStage(
        Long          id,
        Long          pipeId,
        String        stageNo,
        String        status,
        String        nextStageNo,
        LocalDateTime doneTime,
        LocalDateTime ctime,
        LocalDateTime mtime,
        Integer       deleted
    ) {
        this.id = id;
        this.pipeId = pipeId;
        this.stageNo = stageNo;
        this.status = status;
        this.nextStageNo = nextStageNo;
        this.doneTime = doneTime;
        this.ctime = ctime;
        this.mtime = mtime;
        this.deleted = deleted;
    }

    public Long getId() {
        return this.id;
    }

    public ProcessActionStage setId(Long id) {
        this.id = id;
        return this;
    }

    public Long getPipeId() {
        return this.pipeId;
    }

    public ProcessActionStage setPipeId(Long pipeId) {
        this.pipeId = pipeId;
        return this;
    }

    public String getStageNo() {
        return this.stageNo;
    }

    public ProcessActionStage setStageNo(String stageNo) {
        this.stageNo = stageNo;
        return this;
    }

    public String getStatus() {
        return this.status;
    }

    public ProcessActionStage setStatus(String status) {
        this.status = status;
        return this;
    }

    public String getNextStageNo() {
        return this.nextStageNo;
    }

    public ProcessActionStage setNextStageNo(String nextStageNo) {
        this.nextStageNo = nextStageNo;
        return this;
    }

    public LocalDateTime getDoneTime() {
        return this.doneTime;
    }

    public ProcessActionStage setDoneTime(LocalDateTime doneTime) {
        this.doneTime = doneTime;
        return this;
    }

    public LocalDateTime getCtime() {
        return this.ctime;
    }

    public ProcessActionStage setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
        return this;
    }

    public LocalDateTime getMtime() {
        return this.mtime;
    }

    public ProcessActionStage setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
        return this;
    }

    public Integer getDeleted() {
        return this.deleted;
    }

    public ProcessActionStage setDeleted(Integer deleted) {
        this.deleted = deleted;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProcessActionStage (");

        sb.append(id);
        sb.append(", ").append(pipeId);
        sb.append(", ").append(stageNo);
        sb.append(", ").append(status);
        sb.append(", ").append(nextStageNo);
        sb.append(", ").append(doneTime);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);
        sb.append(", ").append(deleted);

        sb.append(")");
        return sb.toString();
    }
}
