/*
 * This file is generated by jOOQ.
 */
package com.merchant.pipeline.db.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * actionGroup
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProcessActionGroup implements Serializable {

    private static final long serialVersionUID = 1956413909;

    private Long          id;
    private String        name;
    private Long          taskId;
    private Long          processId;
    private String        status;
    private LocalDateTime triggerTime;
    private LocalDateTime ctime;
    private LocalDateTime mtime;

    public ProcessActionGroup() {}

    public ProcessActionGroup(ProcessActionGroup value) {
        this.id = value.id;
        this.name = value.name;
        this.taskId = value.taskId;
        this.processId = value.processId;
        this.status = value.status;
        this.triggerTime = value.triggerTime;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
    }

    public ProcessActionGroup(
        Long          id,
        String        name,
        Long          taskId,
        Long          processId,
        String        status,
        LocalDateTime triggerTime,
        LocalDateTime ctime,
        LocalDateTime mtime
    ) {
        this.id = id;
        this.name = name;
        this.taskId = taskId;
        this.processId = processId;
        this.status = status;
        this.triggerTime = triggerTime;
        this.ctime = ctime;
        this.mtime = mtime;
    }

    public Long getId() {
        return this.id;
    }

    public ProcessActionGroup setId(Long id) {
        this.id = id;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public ProcessActionGroup setName(String name) {
        this.name = name;
        return this;
    }

    public Long getTaskId() {
        return this.taskId;
    }

    public ProcessActionGroup setTaskId(Long taskId) {
        this.taskId = taskId;
        return this;
    }

    public Long getProcessId() {
        return this.processId;
    }

    public ProcessActionGroup setProcessId(Long processId) {
        this.processId = processId;
        return this;
    }

    public String getStatus() {
        return this.status;
    }

    public ProcessActionGroup setStatus(String status) {
        this.status = status;
        return this;
    }

    public LocalDateTime getTriggerTime() {
        return this.triggerTime;
    }

    public ProcessActionGroup setTriggerTime(LocalDateTime triggerTime) {
        this.triggerTime = triggerTime;
        return this;
    }

    public LocalDateTime getCtime() {
        return this.ctime;
    }

    public ProcessActionGroup setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
        return this;
    }

    public LocalDateTime getMtime() {
        return this.mtime;
    }

    public ProcessActionGroup setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProcessActionGroup (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(taskId);
        sb.append(", ").append(processId);
        sb.append(", ").append(status);
        sb.append(", ").append(triggerTime);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
