/*
 * This file is generated by jOOQ.
 */
package com.merchant.pipe.db.tables;


import com.merchant.pipe.db.DefaultSchema;
import com.merchant.pipe.db.Indexes;
import com.merchant.pipe.db.Keys;
import com.merchant.pipe.db.tables.records.ProcessActionRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * process_action
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProcessAction extends TableImpl<ProcessActionRecord> {

    private static final long serialVersionUID = -997654990;

    /**
     * The reference instance of <code>process_action</code>
     */
    public static final ProcessAction PROCESS_ACTION = new ProcessAction();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProcessActionRecord> getRecordType() {
        return ProcessActionRecord.class;
    }

    /**
     * The column <code>process_action.id</code>. pk
     */
    public final TableField<ProcessActionRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "pk");

    /**
     * The column <code>process_action.item_no</code>. 流水号
     */
    public final TableField<ProcessActionRecord, String> ITEM_NO = createField(DSL.name("item_no"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "流水号");

    /**
     * The column <code>process_action.pipe_id</code>. pipeId
     */
    public final TableField<ProcessActionRecord, Long> PIPE_ID = createField(DSL.name("pipe_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "pipeId");

    /**
     * The column <code>process_action.stage_no</code>. action 所属的阶段编号
     */
    public final TableField<ProcessActionRecord, String> STAGE_NO = createField(DSL.name("stage_no"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "action 所属的阶段编号");

    /**
     * The column <code>process_action.name</code>. action名称，在actionDef中定义
     */
    public final TableField<ProcessActionRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "action名称，在actionDef中定义");

    /**
     * The column <code>process_action.context</code>. context
     */
    public final TableField<ProcessActionRecord, String> CONTEXT = createField(DSL.name("context"), org.jooq.impl.SQLDataType.CLOB, this, "context");

    /**
     * The column <code>process_action.input_script</code>. input 参数映射脚本
     */
    public final TableField<ProcessActionRecord, String> INPUT_SCRIPT = createField(DSL.name("input_script"), org.jooq.impl.SQLDataType.CLOB, this, "input 参数映射脚本");

    /**
     * The column <code>process_action.clazz</code>. action的实现类，全类名
     */
    public final TableField<ProcessActionRecord, String> CLAZZ = createField(DSL.name("clazz"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "action的实现类，全类名");

    /**
     * The column <code>process_action.param</code>. 请求信息
     */
    public final TableField<ProcessActionRecord, String> PARAM = createField(DSL.name("param"), org.jooq.impl.SQLDataType.CLOB, this, "请求信息");

    /**
     * The column <code>process_action.result</code>. 响应信息
     */
    public final TableField<ProcessActionRecord, String> RESULT = createField(DSL.name("result"), org.jooq.impl.SQLDataType.CLOB, this, "响应信息");

    /**
     * The column <code>process_action.biz_explain</code>. 业务信息说明
     */
    public final TableField<ProcessActionRecord, String> BIZ_EXPLAIN = createField(DSL.name("biz_explain"), org.jooq.impl.SQLDataType.CLOB, this, "业务信息说明");

    /**
     * The column <code>process_action.exec_count</code>. 执行次数
     */
    public final TableField<ProcessActionRecord, Integer> EXEC_COUNT = createField(DSL.name("exec_count"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "执行次数");

    /**
     * The column <code>process_action.err_msg</code>.
     */
    public final TableField<ProcessActionRecord, String> ERR_MSG = createField(DSL.name("err_msg"), org.jooq.impl.SQLDataType.VARCHAR(5120).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>process_action.tip</code>. tractId
     */
    public final TableField<ProcessActionRecord, String> TIP = createField(DSL.name("tip"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "tractId");

    /**
     * The column <code>process_action.task_id</code>. 任务id
     */
    public final TableField<ProcessActionRecord, Long> TASK_ID = createField(DSL.name("task_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "任务id");

    /**
     * The column <code>process_action.task_code</code>. 任务配置id
     */
    public final TableField<ProcessActionRecord, String> TASK_CODE = createField(DSL.name("task_code"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "任务配置id");

    /**
     * The column <code>process_action.process_id</code>. 流程实例id
     */
    public final TableField<ProcessActionRecord, Long> PROCESS_ID = createField(DSL.name("process_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "流程实例id");

    /**
     * The column <code>process_action.status</code>. INIT_FAIL、INIT_SUCC、EXEC_FAIL、EXEC_SUCC、EXEC_SKIP
     */
    public final TableField<ProcessActionRecord, String> STATUS = createField(DSL.name("status"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "INIT_FAIL、INIT_SUCC、EXEC_FAIL、EXEC_SUCC、EXEC_SKIP");

    /**
     * The column <code>process_action.exec_mode</code>. 执行方式: AUTO, MANUAL, SKIP
     */
    public final TableField<ProcessActionRecord, String> EXEC_MODE = createField(DSL.name("exec_mode"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "执行方式: AUTO, MANUAL, SKIP");

    /**
     * The column <code>process_action.ucid</code>. ucid
     */
    public final TableField<ProcessActionRecord, String> UCID = createField(DSL.name("ucid"), org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "ucid");

    /**
     * The column <code>process_action.admin_accounts</code>. 管理员用户名称, 逗号分隔
     */
    public final TableField<ProcessActionRecord, String> ADMIN_ACCOUNTS = createField(DSL.name("admin_accounts"), org.jooq.impl.SQLDataType.VARCHAR(512).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "管理员用户名称, 逗号分隔");

    /**
     * The column <code>process_action.done_time</code>. action 完成时间
     */
    public final TableField<ProcessActionRecord, LocalDateTime> DONE_TIME = createField(DSL.name("done_time"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.inline("1970-01-02 00:00:00", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "action 完成时间");

    /**
     * The column <code>process_action.ctime</code>. ctime
     */
    public final TableField<ProcessActionRecord, LocalDateTime> CTIME = createField(DSL.name("ctime"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.inline("1970-01-02 00:00:00", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "ctime");

    /**
     * The column <code>process_action.mtime</code>. utime
     */
    public final TableField<ProcessActionRecord, LocalDateTime> MTIME = createField(DSL.name("mtime"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.inline("1970-01-02 00:00:00", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "utime");

    /**
     * The column <code>process_action.deleted</code>. 已被删除
     */
    public final TableField<ProcessActionRecord, Integer> DELETED = createField(DSL.name("deleted"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "已被删除");

    /**
     * Create a <code>process_action</code> table reference
     */
    public ProcessAction() {
        this(DSL.name("process_action"), null);
    }

    /**
     * Create an aliased <code>process_action</code> table reference
     */
    public ProcessAction(String alias) {
        this(DSL.name(alias), PROCESS_ACTION);
    }

    /**
     * Create an aliased <code>process_action</code> table reference
     */
    public ProcessAction(Name alias) {
        this(alias, PROCESS_ACTION);
    }

    private ProcessAction(Name alias, Table<ProcessActionRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProcessAction(Name alias, Table<ProcessActionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("process_action"), TableOptions.table());
    }

    public <O extends Record> ProcessAction(Table<O> child, ForeignKey<O, ProcessActionRecord> key) {
        super(child, key, PROCESS_ACTION);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PROCESS_ACTION_PROCESS_ACTION_GROUP_ID_INDEX, Indexes.PROCESS_ACTION_PROCESS_ACTION_ITEM_NO_INDEX, Indexes.PROCESS_ACTION_PROCESS_ACTION_PROCESS_ID_INDEX, Indexes.PROCESS_ACTION_PROCESS_ACTION_STAGE_NO_INDEX, Indexes.PROCESS_ACTION_PROCESS_ACTION_TASK_ID_INDEX);
    }

    @Override
    public Identity<ProcessActionRecord, Long> getIdentity() {
        return Keys.IDENTITY_PROCESS_ACTION;
    }

    @Override
    public UniqueKey<ProcessActionRecord> getPrimaryKey() {
        return Keys.KEY_PROCESS_ACTION_PRIMARY;
    }

    @Override
    public List<UniqueKey<ProcessActionRecord>> getKeys() {
        return Arrays.<UniqueKey<ProcessActionRecord>>asList(Keys.KEY_PROCESS_ACTION_PRIMARY);
    }

    @Override
    public ProcessAction as(String alias) {
        return new ProcessAction(DSL.name(alias), this);
    }

    @Override
    public ProcessAction as(Name alias) {
        return new ProcessAction(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcessAction rename(String name) {
        return new ProcessAction(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcessAction rename(Name name) {
        return new ProcessAction(name, null);
    }
}
