/*
 * This file is generated by jOOQ.
 */
package com.merchant.pipe.db.tables;


import com.merchant.pipe.db.DefaultSchema;
import com.merchant.pipe.db.Indexes;
import com.merchant.pipe.db.Keys;
import com.merchant.pipe.db.tables.records.ProcessActionGroupRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * actionGroup
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProcessActionGroup extends TableImpl<ProcessActionGroupRecord> {

    private static final long serialVersionUID = 1396102060;

    /**
     * The reference instance of <code>process_action_group</code>
     */
    public static final ProcessActionGroup PROCESS_ACTION_GROUP = new ProcessActionGroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProcessActionGroupRecord> getRecordType() {
        return ProcessActionGroupRecord.class;
    }

    /**
     * The column <code>process_action_group.id</code>. pk
     */
    public final TableField<ProcessActionGroupRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "pk");

    /**
     * The column <code>process_action_group.name</code>. name
     */
    public final TableField<ProcessActionGroupRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "name");

    /**
     * The column <code>process_action_group.task_id</code>. taskId
     */
    public final TableField<ProcessActionGroupRecord, Long> TASK_ID = createField(DSL.name("task_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "taskId");

    /**
     * The column <code>process_action_group.process_id</code>. processId
     */
    public final TableField<ProcessActionGroupRecord, Long> PROCESS_ID = createField(DSL.name("process_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "processId");

    /**
     * The column <code>process_action_group.status</code>. status
     */
    public final TableField<ProcessActionGroupRecord, String> STATUS = createField(DSL.name("status"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "status");

    /**
     * The column <code>process_action_group.trigger_time</code>. 定时触发时间
     */
    public final TableField<ProcessActionGroupRecord, LocalDateTime> TRIGGER_TIME = createField(DSL.name("trigger_time"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "定时触发时间");

    /**
     * The column <code>process_action_group.ctime</code>. ctime
     */
    public final TableField<ProcessActionGroupRecord, LocalDateTime> CTIME = createField(DSL.name("ctime"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "ctime");

    /**
     * The column <code>process_action_group.mtime</code>. mtime
     */
    public final TableField<ProcessActionGroupRecord, LocalDateTime> MTIME = createField(DSL.name("mtime"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "mtime");

    /**
     * Create a <code>process_action_group</code> table reference
     */
    public ProcessActionGroup() {
        this(DSL.name("process_action_group"), null);
    }

    /**
     * Create an aliased <code>process_action_group</code> table reference
     */
    public ProcessActionGroup(String alias) {
        this(DSL.name(alias), PROCESS_ACTION_GROUP);
    }

    /**
     * Create an aliased <code>process_action_group</code> table reference
     */
    public ProcessActionGroup(Name alias) {
        this(alias, PROCESS_ACTION_GROUP);
    }

    private ProcessActionGroup(Name alias, Table<ProcessActionGroupRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProcessActionGroup(Name alias, Table<ProcessActionGroupRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("actionGroup"), TableOptions.table());
    }

    public <O extends Record> ProcessActionGroup(Table<O> child, ForeignKey<O, ProcessActionGroupRecord> key) {
        super(child, key, PROCESS_ACTION_GROUP);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PROCESS_ACTION_GROUP_PROCESS_ACTION_GROUP_PROCESSID_IDX, Indexes.PROCESS_ACTION_GROUP_PROCESS_ACTION_GROUP_TASKID_IDX);
    }

    @Override
    public Identity<ProcessActionGroupRecord, Long> getIdentity() {
        return Keys.IDENTITY_PROCESS_ACTION_GROUP;
    }

    @Override
    public UniqueKey<ProcessActionGroupRecord> getPrimaryKey() {
        return Keys.KEY_PROCESS_ACTION_GROUP_PRIMARY;
    }

    @Override
    public List<UniqueKey<ProcessActionGroupRecord>> getKeys() {
        return Arrays.<UniqueKey<ProcessActionGroupRecord>>asList(Keys.KEY_PROCESS_ACTION_GROUP_PRIMARY);
    }

    @Override
    public ProcessActionGroup as(String alias) {
        return new ProcessActionGroup(DSL.name(alias), this);
    }

    @Override
    public ProcessActionGroup as(Name alias) {
        return new ProcessActionGroup(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcessActionGroup rename(String name) {
        return new ProcessActionGroup(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcessActionGroup rename(Name name) {
        return new ProcessActionGroup(name, null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, String, Long, Long, String, LocalDateTime, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }
}
