/*
 * This file is generated by jOOQ.
 */
package com.ke.merchant.kernel.pipe.db.tables;


import com.ke.merchant.kernel.pipe.db.DefaultSchema;
import com.ke.merchant.kernel.pipe.db.Indexes;
import com.ke.merchant.kernel.pipe.db.Keys;
import com.ke.merchant.kernel.pipe.db.tables.records.ProcessActionOpLogRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * Action 操作日志表
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProcessActionOpLog extends TableImpl<ProcessActionOpLogRecord> {

    private static final long serialVersionUID = 1884002851;

    /**
     * The reference instance of <code>process_action_op_log</code>
     */
    public static final ProcessActionOpLog PROCESS_ACTION_OP_LOG = new ProcessActionOpLog();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProcessActionOpLogRecord> getRecordType() {
        return ProcessActionOpLogRecord.class;
    }

    /**
     * The column <code>process_action_op_log.id</code>. PK
     */
    public final TableField<ProcessActionOpLogRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "PK");

    /**
     * The column <code>process_action_op_log.resource_no</code>. resource_no
     */
    public final TableField<ProcessActionOpLogRecord, String> RESOURCE_NO = createField(DSL.name("resource_no"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "resource_no");

    /**
     * The column <code>process_action_op_log.operation_type</code>. 操作类型
     */
    public final TableField<ProcessActionOpLogRecord, String> OPERATION_TYPE = createField(DSL.name("operation_type"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "操作类型");

    /**
     * The column <code>process_action_op_log.operation_time</code>. 执行时间
     */
    public final TableField<ProcessActionOpLogRecord, LocalDateTime> OPERATION_TIME = createField(DSL.name("operation_time"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "执行时间");

    /**
     * The column <code>process_action_op_log.address</code>. 执行机器地址
     */
    public final TableField<ProcessActionOpLogRecord, String> ADDRESS = createField(DSL.name("address"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "执行机器地址");

    /**
     * The column <code>process_action_op_log.username</code>. 用户名
     */
    public final TableField<ProcessActionOpLogRecord, String> USERNAME = createField(DSL.name("username"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "用户名");

    /**
     * The column <code>process_action_op_log.ucid</code>. 用户ucid
     */
    public final TableField<ProcessActionOpLogRecord, Long> UCID = createField(DSL.name("ucid"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "用户ucid");

    /**
     * The column <code>process_action_op_log.ctime</code>. ctime
     */
    public final TableField<ProcessActionOpLogRecord, LocalDateTime> CTIME = createField(DSL.name("ctime"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "ctime");

    /**
     * Create a <code>process_action_op_log</code> table reference
     */
    public ProcessActionOpLog() {
        this(DSL.name("process_action_op_log"), null);
    }

    /**
     * Create an aliased <code>process_action_op_log</code> table reference
     */
    public ProcessActionOpLog(String alias) {
        this(DSL.name(alias), PROCESS_ACTION_OP_LOG);
    }

    /**
     * Create an aliased <code>process_action_op_log</code> table reference
     */
    public ProcessActionOpLog(Name alias) {
        this(alias, PROCESS_ACTION_OP_LOG);
    }

    private ProcessActionOpLog(Name alias, Table<ProcessActionOpLogRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProcessActionOpLog(Name alias, Table<ProcessActionOpLogRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Action 操作日志表"), TableOptions.table());
    }

    public <O extends Record> ProcessActionOpLog(Table<O> child, ForeignKey<O, ProcessActionOpLogRecord> key) {
        super(child, key, PROCESS_ACTION_OP_LOG);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PROCESS_ACTION_OP_LOG_IDX_RESOURCE_NO);
    }

    @Override
    public Identity<ProcessActionOpLogRecord, Long> getIdentity() {
        return Keys.IDENTITY_PROCESS_ACTION_OP_LOG;
    }

    @Override
    public UniqueKey<ProcessActionOpLogRecord> getPrimaryKey() {
        return Keys.KEY_PROCESS_ACTION_OP_LOG_PRIMARY;
    }

    @Override
    public List<UniqueKey<ProcessActionOpLogRecord>> getKeys() {
        return Arrays.<UniqueKey<ProcessActionOpLogRecord>>asList(Keys.KEY_PROCESS_ACTION_OP_LOG_PRIMARY);
    }

    @Override
    public ProcessActionOpLog as(String alias) {
        return new ProcessActionOpLog(DSL.name(alias), this);
    }

    @Override
    public ProcessActionOpLog as(Name alias) {
        return new ProcessActionOpLog(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcessActionOpLog rename(String name) {
        return new ProcessActionOpLog(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcessActionOpLog rename(Name name) {
        return new ProcessActionOpLog(name, null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, String, String, LocalDateTime, String, String, Long, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }
}
