/*
 * This file is generated by jOOQ.
 */
package com.ke.merchant.kernel.pipe.db.tables;


import com.ke.merchant.kernel.pipe.db.DefaultSchema;
import com.ke.merchant.kernel.pipe.db.Indexes;
import com.ke.merchant.kernel.pipe.db.Keys;
import com.ke.merchant.kernel.pipe.db.tables.records.ProcessActionPipeDefRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * Pipe 定义表
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProcessActionPipeDef extends TableImpl<ProcessActionPipeDefRecord> {

    private static final long serialVersionUID = 238413481;

    /**
     * The reference instance of <code>process_action_pipe_def</code>
     */
    public static final ProcessActionPipeDef PROCESS_ACTION_PIPE_DEF = new ProcessActionPipeDef();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProcessActionPipeDefRecord> getRecordType() {
        return ProcessActionPipeDefRecord.class;
    }

    /**
     * The column <code>process_action_pipe_def.id</code>. PK
     */
    public final TableField<ProcessActionPipeDefRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "PK");

    /**
     * The column <code>process_action_pipe_def.name</code>. name
     */
    public final TableField<ProcessActionPipeDefRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "name");

    /**
     * The column <code>process_action_pipe_def.code</code>. code
     */
    public final TableField<ProcessActionPipeDefRecord, String> CODE = createField(DSL.name("code"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "code");

    /**
     * The column <code>process_action_pipe_def.proc_code</code>. proc_code
     */
    public final TableField<ProcessActionPipeDefRecord, String> PROC_CODE = createField(DSL.name("proc_code"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "proc_code");

    /**
     * The column <code>process_action_pipe_def.task_code</code>. task_code
     */
    public final TableField<ProcessActionPipeDefRecord, String> TASK_CODE = createField(DSL.name("task_code"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "task_code");

    /**
     * The column <code>process_action_pipe_def.stage_def</code>. stage_def
     */
    public final TableField<ProcessActionPipeDefRecord, String> STAGE_DEF = createField(DSL.name("stage_def"), org.jooq.impl.SQLDataType.CLOB, this, "stage_def");

    /**
     * The column <code>process_action_pipe_def.ctime</code>. ctime
     */
    public final TableField<ProcessActionPipeDefRecord, LocalDateTime> CTIME = createField(DSL.name("ctime"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "ctime");

    /**
     * The column <code>process_action_pipe_def.mtime</code>. mtime
     */
    public final TableField<ProcessActionPipeDefRecord, LocalDateTime> MTIME = createField(DSL.name("mtime"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "mtime");

    /**
     * The column <code>process_action_pipe_def.deleted</code>. 逻辑删除
     */
    public final TableField<ProcessActionPipeDefRecord, Integer> DELETED = createField(DSL.name("deleted"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "逻辑删除");

    /**
     * Create a <code>process_action_pipe_def</code> table reference
     */
    public ProcessActionPipeDef() {
        this(DSL.name("process_action_pipe_def"), null);
    }

    /**
     * Create an aliased <code>process_action_pipe_def</code> table reference
     */
    public ProcessActionPipeDef(String alias) {
        this(DSL.name(alias), PROCESS_ACTION_PIPE_DEF);
    }

    /**
     * Create an aliased <code>process_action_pipe_def</code> table reference
     */
    public ProcessActionPipeDef(Name alias) {
        this(alias, PROCESS_ACTION_PIPE_DEF);
    }

    private ProcessActionPipeDef(Name alias, Table<ProcessActionPipeDefRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProcessActionPipeDef(Name alias, Table<ProcessActionPipeDefRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Pipe 定义表"), TableOptions.table());
    }

    public <O extends Record> ProcessActionPipeDef(Table<O> child, ForeignKey<O, ProcessActionPipeDefRecord> key) {
        super(child, key, PROCESS_ACTION_PIPE_DEF);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PROCESS_ACTION_PIPE_DEF_PIPE_DEF_CODE_IDX, Indexes.PROCESS_ACTION_PIPE_DEF_PIPE_DEF_PROC_CODE_TASK_CODE_IDX);
    }

    @Override
    public Identity<ProcessActionPipeDefRecord, Long> getIdentity() {
        return Keys.IDENTITY_PROCESS_ACTION_PIPE_DEF;
    }

    @Override
    public UniqueKey<ProcessActionPipeDefRecord> getPrimaryKey() {
        return Keys.KEY_PROCESS_ACTION_PIPE_DEF_PRIMARY;
    }

    @Override
    public List<UniqueKey<ProcessActionPipeDefRecord>> getKeys() {
        return Arrays.<UniqueKey<ProcessActionPipeDefRecord>>asList(Keys.KEY_PROCESS_ACTION_PIPE_DEF_PRIMARY);
    }

    @Override
    public ProcessActionPipeDef as(String alias) {
        return new ProcessActionPipeDef(DSL.name(alias), this);
    }

    @Override
    public ProcessActionPipeDef as(Name alias) {
        return new ProcessActionPipeDef(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcessActionPipeDef rename(String name) {
        return new ProcessActionPipeDef(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcessActionPipeDef rename(Name name) {
        return new ProcessActionPipeDef(name, null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, String, String, String, String, String, LocalDateTime, LocalDateTime, Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }
}
