/*
 * This file is generated by jOOQ.
 */
package com.merchant.pipeline.db.tables;


import com.merchant.kernel.pipe.db.DefaultSchema;
import com.merchant.kernel.pipe.db.Indexes;
import com.merchant.kernel.pipe.db.Keys;
import com.merchant.kernel.pipe.db.tables.records.ProcessActionStageRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * stage 实例表
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProcessActionStage extends TableImpl<ProcessActionStageRecord> {

    private static final long serialVersionUID = -2001200622;

    /**
     * The reference instance of <code>process_action_stage</code>
     */
    public static final ProcessActionStage PROCESS_ACTION_STAGE = new ProcessActionStage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProcessActionStageRecord> getRecordType() {
        return ProcessActionStageRecord.class;
    }

    /**
     * The column <code>process_action_stage.id</code>. PK
     */
    public final TableField<ProcessActionStageRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "PK");

    /**
     * The column <code>process_action_stage.pipe_id</code>. pipe_id
     */
    public final TableField<ProcessActionStageRecord, Long> PIPE_ID = createField(DSL.name("pipe_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "pipe_id");

    /**
     * The column <code>process_action_stage.stage_no</code>. stage_no
     */
    public final TableField<ProcessActionStageRecord, String> STAGE_NO = createField(DSL.name("stage_no"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "stage_no");

    /**
     * The column <code>process_action_stage.status</code>. status
     */
    public final TableField<ProcessActionStageRecord, String> STATUS = createField(DSL.name("status"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "status");

    /**
     * The column <code>process_action_stage.next_stage_no</code>. next_stage_no
     */
    public final TableField<ProcessActionStageRecord, String> NEXT_STAGE_NO = createField(DSL.name("next_stage_no"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "next_stage_no");

    /**
     * The column <code>process_action_stage.done_time</code>. 完成时间
     */
    public final TableField<ProcessActionStageRecord, LocalDateTime> DONE_TIME = createField(DSL.name("done_time"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.inline("1970-01-02 00:00:00", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "完成时间");

    /**
     * The column <code>process_action_stage.ctime</code>. ctime
     */
    public final TableField<ProcessActionStageRecord, LocalDateTime> CTIME = createField(DSL.name("ctime"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "ctime");

    /**
     * The column <code>process_action_stage.mtime</code>. mtime
     */
    public final TableField<ProcessActionStageRecord, LocalDateTime> MTIME = createField(DSL.name("mtime"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "mtime");

    /**
     * The column <code>process_action_stage.deleted</code>. 逻辑删除
     */
    public final TableField<ProcessActionStageRecord, Integer> DELETED = createField(DSL.name("deleted"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "逻辑删除");

    /**
     * Create a <code>process_action_stage</code> table reference
     */
    public ProcessActionStage() {
        this(DSL.name("process_action_stage"), null);
    }

    /**
     * Create an aliased <code>process_action_stage</code> table reference
     */
    public ProcessActionStage(String alias) {
        this(DSL.name(alias), PROCESS_ACTION_STAGE);
    }

    /**
     * Create an aliased <code>process_action_stage</code> table reference
     */
    public ProcessActionStage(Name alias) {
        this(alias, PROCESS_ACTION_STAGE);
    }

    private ProcessActionStage(Name alias, Table<ProcessActionStageRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProcessActionStage(Name alias, Table<ProcessActionStageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("stage 实例表"), TableOptions.table());
    }

    public <O extends Record> ProcessActionStage(Table<O> child, ForeignKey<O, ProcessActionStageRecord> key) {
        super(child, key, PROCESS_ACTION_STAGE);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PROCESS_ACTION_STAGE_PIPE_STAGE_STAGE_NO_IDX);
    }

    @Override
    public Identity<ProcessActionStageRecord, Long> getIdentity() {
        return Keys.IDENTITY_PROCESS_ACTION_STAGE;
    }

    @Override
    public UniqueKey<ProcessActionStageRecord> getPrimaryKey() {
        return Keys.KEY_PROCESS_ACTION_STAGE_PRIMARY;
    }

    @Override
    public List<UniqueKey<ProcessActionStageRecord>> getKeys() {
        return Arrays.<UniqueKey<ProcessActionStageRecord>>asList(Keys.KEY_PROCESS_ACTION_STAGE_PRIMARY);
    }

    @Override
    public ProcessActionStage as(String alias) {
        return new ProcessActionStage(DSL.name(alias), this);
    }

    @Override
    public ProcessActionStage as(Name alias) {
        return new ProcessActionStage(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcessActionStage rename(String name) {
        return new ProcessActionStage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcessActionStage rename(Name name) {
        return new ProcessActionStage(name, null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, Long, String, String, String, LocalDateTime, LocalDateTime, LocalDateTime, Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }
}
