/*
 * This file is generated by jOOQ.
 */
package com.merchant.pipeline.db.tables.records;


import com.merchant.kernel.pipe.db.tables.ProcessActionStage;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * stage 实例表
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProcessActionStageRecord extends UpdatableRecordImpl<ProcessActionStageRecord> implements Record9<Long, Long, String, String, String, LocalDateTime, LocalDateTime, LocalDateTime, Integer> {

    private static final long serialVersionUID = -1879292650;

    /**
     * Setter for <code>process_action_stage.id</code>. PK
     */
    public ProcessActionStageRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>process_action_stage.id</code>. PK
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>process_action_stage.pipe_id</code>. pipe_id
     */
    public ProcessActionStageRecord setPipeId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>process_action_stage.pipe_id</code>. pipe_id
     */
    public Long getPipeId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>process_action_stage.stage_no</code>. stage_no
     */
    public ProcessActionStageRecord setStageNo(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>process_action_stage.stage_no</code>. stage_no
     */
    public String getStageNo() {
        return (String) get(2);
    }

    /**
     * Setter for <code>process_action_stage.status</code>. status
     */
    public ProcessActionStageRecord setStatus(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>process_action_stage.status</code>. status
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>process_action_stage.next_stage_no</code>. next_stage_no
     */
    public ProcessActionStageRecord setNextStageNo(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>process_action_stage.next_stage_no</code>. next_stage_no
     */
    public String getNextStageNo() {
        return (String) get(4);
    }

    /**
     * Setter for <code>process_action_stage.done_time</code>. 完成时间
     */
    public ProcessActionStageRecord setDoneTime(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>process_action_stage.done_time</code>. 完成时间
     */
    public LocalDateTime getDoneTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>process_action_stage.ctime</code>. ctime
     */
    public ProcessActionStageRecord setCtime(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>process_action_stage.ctime</code>. ctime
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>process_action_stage.mtime</code>. mtime
     */
    public ProcessActionStageRecord setMtime(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>process_action_stage.mtime</code>. mtime
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>process_action_stage.deleted</code>. 逻辑删除
     */
    public ProcessActionStageRecord setDeleted(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>process_action_stage.deleted</code>. 逻辑删除
     */
    public Integer getDeleted() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, Long, String, String, String, LocalDateTime, LocalDateTime, LocalDateTime, Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, Long, String, String, String, LocalDateTime, LocalDateTime, LocalDateTime, Integer> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ProcessActionStage.PROCESS_ACTION_STAGE.ID;
    }

    @Override
    public Field<Long> field2() {
        return ProcessActionStage.PROCESS_ACTION_STAGE.PIPE_ID;
    }

    @Override
    public Field<String> field3() {
        return ProcessActionStage.PROCESS_ACTION_STAGE.STAGE_NO;
    }

    @Override
    public Field<String> field4() {
        return ProcessActionStage.PROCESS_ACTION_STAGE.STATUS;
    }

    @Override
    public Field<String> field5() {
        return ProcessActionStage.PROCESS_ACTION_STAGE.NEXT_STAGE_NO;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return ProcessActionStage.PROCESS_ACTION_STAGE.DONE_TIME;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return ProcessActionStage.PROCESS_ACTION_STAGE.CTIME;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return ProcessActionStage.PROCESS_ACTION_STAGE.MTIME;
    }

    @Override
    public Field<Integer> field9() {
        return ProcessActionStage.PROCESS_ACTION_STAGE.DELETED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getPipeId();
    }

    @Override
    public String component3() {
        return getStageNo();
    }

    @Override
    public String component4() {
        return getStatus();
    }

    @Override
    public String component5() {
        return getNextStageNo();
    }

    @Override
    public LocalDateTime component6() {
        return getDoneTime();
    }

    @Override
    public LocalDateTime component7() {
        return getCtime();
    }

    @Override
    public LocalDateTime component8() {
        return getMtime();
    }

    @Override
    public Integer component9() {
        return getDeleted();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getPipeId();
    }

    @Override
    public String value3() {
        return getStageNo();
    }

    @Override
    public String value4() {
        return getStatus();
    }

    @Override
    public String value5() {
        return getNextStageNo();
    }

    @Override
    public LocalDateTime value6() {
        return getDoneTime();
    }

    @Override
    public LocalDateTime value7() {
        return getCtime();
    }

    @Override
    public LocalDateTime value8() {
        return getMtime();
    }

    @Override
    public Integer value9() {
        return getDeleted();
    }

    @Override
    public ProcessActionStageRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ProcessActionStageRecord value2(Long value) {
        setPipeId(value);
        return this;
    }

    @Override
    public ProcessActionStageRecord value3(String value) {
        setStageNo(value);
        return this;
    }

    @Override
    public ProcessActionStageRecord value4(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public ProcessActionStageRecord value5(String value) {
        setNextStageNo(value);
        return this;
    }

    @Override
    public ProcessActionStageRecord value6(LocalDateTime value) {
        setDoneTime(value);
        return this;
    }

    @Override
    public ProcessActionStageRecord value7(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public ProcessActionStageRecord value8(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public ProcessActionStageRecord value9(Integer value) {
        setDeleted(value);
        return this;
    }

    @Override
    public ProcessActionStageRecord values(Long value1, Long value2, String value3, String value4, String value5, LocalDateTime value6, LocalDateTime value7, LocalDateTime value8, Integer value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProcessActionStageRecord
     */
    public ProcessActionStageRecord() {
        super(ProcessActionStage.PROCESS_ACTION_STAGE);
    }

    /**
     * Create a detached, initialised ProcessActionStageRecord
     */
    public ProcessActionStageRecord(Long id, Long pipeId, String stageNo, String status, String nextStageNo, LocalDateTime doneTime, LocalDateTime ctime, LocalDateTime mtime, Integer deleted) {
        super(ProcessActionStage.PROCESS_ACTION_STAGE);

        set(0, id);
        set(1, pipeId);
        set(2, stageNo);
        set(3, status);
        set(4, nextStageNo);
        set(5, doneTime);
        set(6, ctime);
        set(7, mtime);
        set(8, deleted);
    }
}
