/*
 * This file is generated by jOOQ.
 */
package com.merchant.pipeline.db;


import com.merchant.kernel.pipe.db.tables.FlywaySchemaHistory;
import com.merchant.kernel.pipe.db.tables.ProcessAction;
import com.merchant.kernel.pipe.db.tables.ProcessActionGroup;
import com.merchant.kernel.pipe.db.tables.ProcessActionOpLog;
import com.merchant.kernel.pipe.db.tables.ProcessActionPipe;
import com.merchant.kernel.pipe.db.tables.ProcessActionPipeDef;
import com.merchant.kernel.pipe.db.tables.ProcessActionStage;
import com.merchant.kernel.pipe.db.tables.records.FlywaySchemaHistoryRecord;
import com.merchant.kernel.pipe.db.tables.records.ProcessActionGroupRecord;
import com.merchant.kernel.pipe.db.tables.records.ProcessActionOpLogRecord;
import com.merchant.kernel.pipe.db.tables.records.ProcessActionPipeDefRecord;
import com.merchant.kernel.pipe.db.tables.records.ProcessActionPipeRecord;
import com.merchant.kernel.pipe.db.tables.records.ProcessActionRecord;
import com.merchant.kernel.pipe.db.tables.records.ProcessActionStageRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ProcessActionRecord, Long> IDENTITY_PROCESS_ACTION = Identities0.IDENTITY_PROCESS_ACTION;
    public static final Identity<ProcessActionGroupRecord, Long> IDENTITY_PROCESS_ACTION_GROUP = Identities0.IDENTITY_PROCESS_ACTION_GROUP;
    public static final Identity<ProcessActionOpLogRecord, Long> IDENTITY_PROCESS_ACTION_OP_LOG = Identities0.IDENTITY_PROCESS_ACTION_OP_LOG;
    public static final Identity<ProcessActionPipeRecord, Long> IDENTITY_PROCESS_ACTION_PIPE = Identities0.IDENTITY_PROCESS_ACTION_PIPE;
    public static final Identity<ProcessActionPipeDefRecord, Long> IDENTITY_PROCESS_ACTION_PIPE_DEF = Identities0.IDENTITY_PROCESS_ACTION_PIPE_DEF;
    public static final Identity<ProcessActionStageRecord, Long> IDENTITY_PROCESS_ACTION_STAGE = Identities0.IDENTITY_PROCESS_ACTION_STAGE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FlywaySchemaHistoryRecord> KEY_FLYWAY_SCHEMA_HISTORY_PRIMARY = UniqueKeys0.KEY_FLYWAY_SCHEMA_HISTORY_PRIMARY;
    public static final UniqueKey<ProcessActionRecord> KEY_PROCESS_ACTION_PRIMARY = UniqueKeys0.KEY_PROCESS_ACTION_PRIMARY;
    public static final UniqueKey<ProcessActionGroupRecord> KEY_PROCESS_ACTION_GROUP_PRIMARY = UniqueKeys0.KEY_PROCESS_ACTION_GROUP_PRIMARY;
    public static final UniqueKey<ProcessActionOpLogRecord> KEY_PROCESS_ACTION_OP_LOG_PRIMARY = UniqueKeys0.KEY_PROCESS_ACTION_OP_LOG_PRIMARY;
    public static final UniqueKey<ProcessActionPipeRecord> KEY_PROCESS_ACTION_PIPE_PRIMARY = UniqueKeys0.KEY_PROCESS_ACTION_PIPE_PRIMARY;
    public static final UniqueKey<ProcessActionPipeDefRecord> KEY_PROCESS_ACTION_PIPE_DEF_PRIMARY = UniqueKeys0.KEY_PROCESS_ACTION_PIPE_DEF_PRIMARY;
    public static final UniqueKey<ProcessActionStageRecord> KEY_PROCESS_ACTION_STAGE_PRIMARY = UniqueKeys0.KEY_PROCESS_ACTION_STAGE_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<ProcessActionRecord, Long> IDENTITY_PROCESS_ACTION = Internal.createIdentity(ProcessAction.PROCESS_ACTION, ProcessAction.PROCESS_ACTION.ID);
        public static Identity<ProcessActionGroupRecord, Long> IDENTITY_PROCESS_ACTION_GROUP = Internal.createIdentity(ProcessActionGroup.PROCESS_ACTION_GROUP, ProcessActionGroup.PROCESS_ACTION_GROUP.ID);
        public static Identity<ProcessActionOpLogRecord, Long> IDENTITY_PROCESS_ACTION_OP_LOG = Internal.createIdentity(ProcessActionOpLog.PROCESS_ACTION_OP_LOG, ProcessActionOpLog.PROCESS_ACTION_OP_LOG.ID);
        public static Identity<ProcessActionPipeRecord, Long> IDENTITY_PROCESS_ACTION_PIPE = Internal.createIdentity(ProcessActionPipe.PROCESS_ACTION_PIPE, ProcessActionPipe.PROCESS_ACTION_PIPE.ID);
        public static Identity<ProcessActionPipeDefRecord, Long> IDENTITY_PROCESS_ACTION_PIPE_DEF = Internal.createIdentity(ProcessActionPipeDef.PROCESS_ACTION_PIPE_DEF, ProcessActionPipeDef.PROCESS_ACTION_PIPE_DEF.ID);
        public static Identity<ProcessActionStageRecord, Long> IDENTITY_PROCESS_ACTION_STAGE = Internal.createIdentity(ProcessActionStage.PROCESS_ACTION_STAGE, ProcessActionStage.PROCESS_ACTION_STAGE.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<FlywaySchemaHistoryRecord> KEY_FLYWAY_SCHEMA_HISTORY_PRIMARY = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, "KEY_flyway_schema_history_PRIMARY", new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
        public static final UniqueKey<ProcessActionRecord> KEY_PROCESS_ACTION_PRIMARY = Internal.createUniqueKey(ProcessAction.PROCESS_ACTION, "KEY_process_action_PRIMARY", new TableField[] { ProcessAction.PROCESS_ACTION.ID }, true);
        public static final UniqueKey<ProcessActionGroupRecord> KEY_PROCESS_ACTION_GROUP_PRIMARY = Internal.createUniqueKey(ProcessActionGroup.PROCESS_ACTION_GROUP, "KEY_process_action_group_PRIMARY", new TableField[] { ProcessActionGroup.PROCESS_ACTION_GROUP.ID }, true);
        public static final UniqueKey<ProcessActionOpLogRecord> KEY_PROCESS_ACTION_OP_LOG_PRIMARY = Internal.createUniqueKey(ProcessActionOpLog.PROCESS_ACTION_OP_LOG, "KEY_process_action_op_log_PRIMARY", new TableField[] { ProcessActionOpLog.PROCESS_ACTION_OP_LOG.ID }, true);
        public static final UniqueKey<ProcessActionPipeRecord> KEY_PROCESS_ACTION_PIPE_PRIMARY = Internal.createUniqueKey(ProcessActionPipe.PROCESS_ACTION_PIPE, "KEY_process_action_pipe_PRIMARY", new TableField[] { ProcessActionPipe.PROCESS_ACTION_PIPE.ID }, true);
        public static final UniqueKey<ProcessActionPipeDefRecord> KEY_PROCESS_ACTION_PIPE_DEF_PRIMARY = Internal.createUniqueKey(ProcessActionPipeDef.PROCESS_ACTION_PIPE_DEF, "KEY_process_action_pipe_def_PRIMARY", new TableField[] { ProcessActionPipeDef.PROCESS_ACTION_PIPE_DEF.ID }, true);
        public static final UniqueKey<ProcessActionStageRecord> KEY_PROCESS_ACTION_STAGE_PRIMARY = Internal.createUniqueKey(ProcessActionStage.PROCESS_ACTION_STAGE, "KEY_process_action_stage_PRIMARY", new TableField[] { ProcessActionStage.PROCESS_ACTION_STAGE.ID }, true);
    }
}
