/*
 * This file is generated by jOOQ.
 */
package com.merchant.pipe.db;


import com.merchant.pipe.db.tables.FlywaySchemaHistory;
import com.merchant.pipe.db.tables.ProcessAction;
import com.merchant.pipe.db.tables.ProcessActionGroup;
import com.merchant.pipe.db.tables.ProcessActionOpLog;
import com.merchant.pipe.db.tables.ProcessActionPipe;
import com.merchant.pipe.db.tables.ProcessActionPipeDef;
import com.merchant.pipe.db.tables.ProcessActionStage;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = -184199227;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * process_action
     */
    public final ProcessAction PROCESS_ACTION = ProcessAction.PROCESS_ACTION;

    /**
     * actionGroup
     */
    public final ProcessActionGroup PROCESS_ACTION_GROUP = ProcessActionGroup.PROCESS_ACTION_GROUP;

    /**
     * Action 操作日志表
     */
    public final ProcessActionOpLog PROCESS_ACTION_OP_LOG = ProcessActionOpLog.PROCESS_ACTION_OP_LOG;

    /**
     * actionPipe
     */
    public final ProcessActionPipe PROCESS_ACTION_PIPE = ProcessActionPipe.PROCESS_ACTION_PIPE;

    /**
     * Pipe 定义表
     */
    public final ProcessActionPipeDef PROCESS_ACTION_PIPE_DEF = ProcessActionPipeDef.PROCESS_ACTION_PIPE_DEF;

    /**
     * stage 实例表
     */
    public final ProcessActionStage PROCESS_ACTION_STAGE = ProcessActionStage.PROCESS_ACTION_STAGE;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            ProcessAction.PROCESS_ACTION,
            ProcessActionGroup.PROCESS_ACTION_GROUP,
            ProcessActionOpLog.PROCESS_ACTION_OP_LOG,
            ProcessActionPipe.PROCESS_ACTION_PIPE,
            ProcessActionPipeDef.PROCESS_ACTION_PIPE_DEF,
            ProcessActionStage.PROCESS_ACTION_STAGE);
    }
}
