/*
 * This file is generated by jOOQ.
 */
package com.merchant.pipe.db;


import com.merchant.pipe.db.tables.FlywaySchemaHistory;
import com.merchant.pipe.db.tables.ProcessAction;
import com.merchant.pipe.db.tables.ProcessActionGroup;
import com.merchant.pipe.db.tables.ProcessActionOpLog;
import com.merchant.pipe.db.tables.ProcessActionPipe;
import com.merchant.pipe.db.tables.ProcessActionPipeDef;
import com.merchant.pipe.db.tables.ProcessActionStage;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FLYWAY_SCHEMA_HISTORY_FLYWAY_SCHEMA_HISTORY_S_IDX = Indexes0.FLYWAY_SCHEMA_HISTORY_FLYWAY_SCHEMA_HISTORY_S_IDX;
    public static final Index PROCESS_ACTION_PROCESS_ACTION_GROUP_ID_INDEX = Indexes0.PROCESS_ACTION_PROCESS_ACTION_GROUP_ID_INDEX;
    public static final Index PROCESS_ACTION_PROCESS_ACTION_ITEM_NO_INDEX = Indexes0.PROCESS_ACTION_PROCESS_ACTION_ITEM_NO_INDEX;
    public static final Index PROCESS_ACTION_PROCESS_ACTION_PROCESS_ID_INDEX = Indexes0.PROCESS_ACTION_PROCESS_ACTION_PROCESS_ID_INDEX;
    public static final Index PROCESS_ACTION_PROCESS_ACTION_STAGE_NO_INDEX = Indexes0.PROCESS_ACTION_PROCESS_ACTION_STAGE_NO_INDEX;
    public static final Index PROCESS_ACTION_PROCESS_ACTION_TASK_ID_INDEX = Indexes0.PROCESS_ACTION_PROCESS_ACTION_TASK_ID_INDEX;
    public static final Index PROCESS_ACTION_GROUP_PROCESS_ACTION_GROUP_PROCESSID_IDX = Indexes0.PROCESS_ACTION_GROUP_PROCESS_ACTION_GROUP_PROCESSID_IDX;
    public static final Index PROCESS_ACTION_GROUP_PROCESS_ACTION_GROUP_TASKID_IDX = Indexes0.PROCESS_ACTION_GROUP_PROCESS_ACTION_GROUP_TASKID_IDX;
    public static final Index PROCESS_ACTION_OP_LOG_IDX_RESOURCE_NO = Indexes0.PROCESS_ACTION_OP_LOG_IDX_RESOURCE_NO;
    public static final Index PROCESS_ACTION_PIPE_PROCESS_ACTION_GROUP_PROCESSID_IDX = Indexes0.PROCESS_ACTION_PIPE_PROCESS_ACTION_GROUP_PROCESSID_IDX;
    public static final Index PROCESS_ACTION_PIPE_PROCESS_ACTION_GROUP_TASKID_IDX = Indexes0.PROCESS_ACTION_PIPE_PROCESS_ACTION_GROUP_TASKID_IDX;
    public static final Index PROCESS_ACTION_PIPE_DEF_PIPE_DEF_CODE_IDX = Indexes0.PROCESS_ACTION_PIPE_DEF_PIPE_DEF_CODE_IDX;
    public static final Index PROCESS_ACTION_PIPE_DEF_PIPE_DEF_PROC_CODE_TASK_CODE_IDX = Indexes0.PROCESS_ACTION_PIPE_DEF_PIPE_DEF_PROC_CODE_TASK_CODE_IDX;
    public static final Index PROCESS_ACTION_STAGE_PIPE_STAGE_STAGE_NO_IDX = Indexes0.PROCESS_ACTION_STAGE_PIPE_STAGE_STAGE_NO_IDX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index FLYWAY_SCHEMA_HISTORY_FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex("flyway_schema_history_s_idx", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
        public static Index PROCESS_ACTION_PROCESS_ACTION_GROUP_ID_INDEX = Internal.createIndex("process_action_group_id_index", ProcessAction.PROCESS_ACTION, new OrderField[] { ProcessAction.PROCESS_ACTION.PIPE_ID }, false);
        public static Index PROCESS_ACTION_PROCESS_ACTION_ITEM_NO_INDEX = Internal.createIndex("process_action_item_no_index", ProcessAction.PROCESS_ACTION, new OrderField[] { ProcessAction.PROCESS_ACTION.ITEM_NO }, false);
        public static Index PROCESS_ACTION_PROCESS_ACTION_PROCESS_ID_INDEX = Internal.createIndex("process_action_process_id_index", ProcessAction.PROCESS_ACTION, new OrderField[] { ProcessAction.PROCESS_ACTION.PROCESS_ID }, false);
        public static Index PROCESS_ACTION_PROCESS_ACTION_STAGE_NO_INDEX = Internal.createIndex("process_action_stage_no_index", ProcessAction.PROCESS_ACTION, new OrderField[] { ProcessAction.PROCESS_ACTION.STAGE_NO }, false);
        public static Index PROCESS_ACTION_PROCESS_ACTION_TASK_ID_INDEX = Internal.createIndex("process_action_task_id_index", ProcessAction.PROCESS_ACTION, new OrderField[] { ProcessAction.PROCESS_ACTION.TASK_ID }, false);
        public static Index PROCESS_ACTION_GROUP_PROCESS_ACTION_GROUP_PROCESSID_IDX = Internal.createIndex("process_action_group_processId_idx", ProcessActionGroup.PROCESS_ACTION_GROUP, new OrderField[] { ProcessActionGroup.PROCESS_ACTION_GROUP.PROCESS_ID }, false);
        public static Index PROCESS_ACTION_GROUP_PROCESS_ACTION_GROUP_TASKID_IDX = Internal.createIndex("process_action_group_taskId_idx", ProcessActionGroup.PROCESS_ACTION_GROUP, new OrderField[] { ProcessActionGroup.PROCESS_ACTION_GROUP.TASK_ID }, false);
        public static Index PROCESS_ACTION_OP_LOG_IDX_RESOURCE_NO = Internal.createIndex("idx_resource_no", ProcessActionOpLog.PROCESS_ACTION_OP_LOG, new OrderField[] { ProcessActionOpLog.PROCESS_ACTION_OP_LOG.RESOURCE_NO }, false);
        public static Index PROCESS_ACTION_PIPE_PROCESS_ACTION_GROUP_PROCESSID_IDX = Internal.createIndex("process_action_group_processId_idx", ProcessActionPipe.PROCESS_ACTION_PIPE, new OrderField[] { ProcessActionPipe.PROCESS_ACTION_PIPE.PROCESS_ID }, false);
        public static Index PROCESS_ACTION_PIPE_PROCESS_ACTION_GROUP_TASKID_IDX = Internal.createIndex("process_action_group_taskId_idx", ProcessActionPipe.PROCESS_ACTION_PIPE, new OrderField[] { ProcessActionPipe.PROCESS_ACTION_PIPE.TASK_ID }, false);
        public static Index PROCESS_ACTION_PIPE_DEF_PIPE_DEF_CODE_IDX = Internal.createIndex("pipe_def_code_idx", ProcessActionPipeDef.PROCESS_ACTION_PIPE_DEF, new OrderField[] { ProcessActionPipeDef.PROCESS_ACTION_PIPE_DEF.CODE }, false);
        public static Index PROCESS_ACTION_PIPE_DEF_PIPE_DEF_PROC_CODE_TASK_CODE_IDX = Internal.createIndex("pipe_def_proc_code_task_code_idx", ProcessActionPipeDef.PROCESS_ACTION_PIPE_DEF, new OrderField[] { ProcessActionPipeDef.PROCESS_ACTION_PIPE_DEF.PROC_CODE, ProcessActionPipeDef.PROCESS_ACTION_PIPE_DEF.TASK_CODE }, false);
        public static Index PROCESS_ACTION_STAGE_PIPE_STAGE_STAGE_NO_IDX = Internal.createIndex("pipe_stage_stage_no_idx", ProcessActionStage.PROCESS_ACTION_STAGE, new OrderField[] { ProcessActionStage.PROCESS_ACTION_STAGE.STAGE_NO }, false);
    }
}
