/*
 * This file is generated by jOOQ.
 */
package com.ke.merchant.kernel.pipe.db;


import com.ke.merchant.kernel.pipe.db.tables.FlywaySchemaHistory;
import com.ke.merchant.kernel.pipe.db.tables.ProcessAction;
import com.ke.merchant.kernel.pipe.db.tables.ProcessActionGroup;
import com.ke.merchant.kernel.pipe.db.tables.ProcessActionOpLog;
import com.ke.merchant.kernel.pipe.db.tables.ProcessActionPipe;
import com.ke.merchant.kernel.pipe.db.tables.ProcessActionPipeDef;
import com.ke.merchant.kernel.pipe.db.tables.ProcessActionStage;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * process_action
     */
    public static final ProcessAction PROCESS_ACTION = ProcessAction.PROCESS_ACTION;

    /**
     * actionGroup
     */
    public static final ProcessActionGroup PROCESS_ACTION_GROUP = ProcessActionGroup.PROCESS_ACTION_GROUP;

    /**
     * Action 操作日志表
     */
    public static final ProcessActionOpLog PROCESS_ACTION_OP_LOG = ProcessActionOpLog.PROCESS_ACTION_OP_LOG;

    /**
     * actionPipe
     */
    public static final ProcessActionPipe PROCESS_ACTION_PIPE = ProcessActionPipe.PROCESS_ACTION_PIPE;

    /**
     * Pipe 定义表
     */
    public static final ProcessActionPipeDef PROCESS_ACTION_PIPE_DEF = ProcessActionPipeDef.PROCESS_ACTION_PIPE_DEF;

    /**
     * stage 实例表
     */
    public static final ProcessActionStage PROCESS_ACTION_STAGE = ProcessActionStage.PROCESS_ACTION_STAGE;
}
