/*
 * This file is generated by jOOQ.
 */
package com.merchant.pipe.db.tables.records;


import com.merchant.pipe.db.tables.ProcessActionPipe;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * actionPipe
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProcessActionPipeRecord extends UpdatableRecordImpl<ProcessActionPipeRecord> implements Record14<Long, String, Long, Long, String, String, String, String, LocalDateTime, LocalDateTime, LocalDateTime, LocalDateTime, String, Integer> {

    private static final long serialVersionUID = -1933364722;

    /**
     * Setter for <code>process_action_pipe.id</code>. pk
     */
    public ProcessActionPipeRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>process_action_pipe.id</code>. pk
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>process_action_pipe.name</code>. name
     */
    public ProcessActionPipeRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>process_action_pipe.name</code>. name
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>process_action_pipe.task_id</code>. taskId
     */
    public ProcessActionPipeRecord setTaskId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>process_action_pipe.task_id</code>. taskId
     */
    public Long getTaskId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>process_action_pipe.process_id</code>. processId
     */
    public ProcessActionPipeRecord setProcessId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>process_action_pipe.process_id</code>. processId
     */
    public Long getProcessId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>process_action_pipe.context</code>. pipe 上下文
     */
    public ProcessActionPipeRecord setContext(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>process_action_pipe.context</code>. pipe 上下文
     */
    public String getContext() {
        return (String) get(4);
    }

    /**
     * Setter for <code>process_action_pipe.status</code>. status
     */
    public ProcessActionPipeRecord setStatus(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>process_action_pipe.status</code>. status
     */
    public String getStatus() {
        return (String) get(5);
    }

    /**
     * Setter for <code>process_action_pipe.head_stage_no</code>. 头结点 stageNo
     */
    public ProcessActionPipeRecord setHeadStageNo(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>process_action_pipe.head_stage_no</code>. 头结点 stageNo
     */
    public String getHeadStageNo() {
        return (String) get(6);
    }

    /**
     * Setter for <code>process_action_pipe.tail_stage_no</code>. 尾节点 stageNo
     */
    public ProcessActionPipeRecord setTailStageNo(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>process_action_pipe.tail_stage_no</code>. 尾节点 stageNo
     */
    public String getTailStageNo() {
        return (String) get(7);
    }

    /**
     * Setter for <code>process_action_pipe.trigger_time</code>. 定时触发时间
     */
    public ProcessActionPipeRecord setTriggerTime(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>process_action_pipe.trigger_time</code>. 定时触发时间
     */
    public LocalDateTime getTriggerTime() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>process_action_pipe.done_time</code>. 完成时间
     */
    public ProcessActionPipeRecord setDoneTime(LocalDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>process_action_pipe.done_time</code>. 完成时间
     */
    public LocalDateTime getDoneTime() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>process_action_pipe.ctime</code>. ctime
     */
    public ProcessActionPipeRecord setCtime(LocalDateTime value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>process_action_pipe.ctime</code>. ctime
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>process_action_pipe.mtime</code>. mtime
     */
    public ProcessActionPipeRecord setMtime(LocalDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>process_action_pipe.mtime</code>. mtime
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>process_action_pipe.pipe_organizer</code>. 主办人
     */
    public ProcessActionPipeRecord setPipeOrganizer(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>process_action_pipe.pipe_organizer</code>. 主办人
     */
    public String getPipeOrganizer() {
        return (String) get(12);
    }

    /**
     * Setter for <code>process_action_pipe.pipe_type</code>. 并网类型
     */
    public ProcessActionPipeRecord setPipeType(Integer value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>process_action_pipe.pipe_type</code>. 并网类型
     */
    public Integer getPipeType() {
        return (Integer) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<Long, String, Long, Long, String, String, String, String, LocalDateTime, LocalDateTime, LocalDateTime, LocalDateTime, String, Integer> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Long, String, Long, Long, String, String, String, String, LocalDateTime, LocalDateTime, LocalDateTime, LocalDateTime, String, Integer> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ProcessActionPipe.PROCESS_ACTION_PIPE.ID;
    }

    @Override
    public Field<String> field2() {
        return ProcessActionPipe.PROCESS_ACTION_PIPE.NAME;
    }

    @Override
    public Field<Long> field3() {
        return ProcessActionPipe.PROCESS_ACTION_PIPE.TASK_ID;
    }

    @Override
    public Field<Long> field4() {
        return ProcessActionPipe.PROCESS_ACTION_PIPE.PROCESS_ID;
    }

    @Override
    public Field<String> field5() {
        return ProcessActionPipe.PROCESS_ACTION_PIPE.CONTEXT;
    }

    @Override
    public Field<String> field6() {
        return ProcessActionPipe.PROCESS_ACTION_PIPE.STATUS;
    }

    @Override
    public Field<String> field7() {
        return ProcessActionPipe.PROCESS_ACTION_PIPE.HEAD_STAGE_NO;
    }

    @Override
    public Field<String> field8() {
        return ProcessActionPipe.PROCESS_ACTION_PIPE.TAIL_STAGE_NO;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return ProcessActionPipe.PROCESS_ACTION_PIPE.TRIGGER_TIME;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return ProcessActionPipe.PROCESS_ACTION_PIPE.DONE_TIME;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return ProcessActionPipe.PROCESS_ACTION_PIPE.CTIME;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return ProcessActionPipe.PROCESS_ACTION_PIPE.MTIME;
    }

    @Override
    public Field<String> field13() {
        return ProcessActionPipe.PROCESS_ACTION_PIPE.PIPE_ORGANIZER;
    }

    @Override
    public Field<Integer> field14() {
        return ProcessActionPipe.PROCESS_ACTION_PIPE.PIPE_TYPE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Long component3() {
        return getTaskId();
    }

    @Override
    public Long component4() {
        return getProcessId();
    }

    @Override
    public String component5() {
        return getContext();
    }

    @Override
    public String component6() {
        return getStatus();
    }

    @Override
    public String component7() {
        return getHeadStageNo();
    }

    @Override
    public String component8() {
        return getTailStageNo();
    }

    @Override
    public LocalDateTime component9() {
        return getTriggerTime();
    }

    @Override
    public LocalDateTime component10() {
        return getDoneTime();
    }

    @Override
    public LocalDateTime component11() {
        return getCtime();
    }

    @Override
    public LocalDateTime component12() {
        return getMtime();
    }

    @Override
    public String component13() {
        return getPipeOrganizer();
    }

    @Override
    public Integer component14() {
        return getPipeType();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Long value3() {
        return getTaskId();
    }

    @Override
    public Long value4() {
        return getProcessId();
    }

    @Override
    public String value5() {
        return getContext();
    }

    @Override
    public String value6() {
        return getStatus();
    }

    @Override
    public String value7() {
        return getHeadStageNo();
    }

    @Override
    public String value8() {
        return getTailStageNo();
    }

    @Override
    public LocalDateTime value9() {
        return getTriggerTime();
    }

    @Override
    public LocalDateTime value10() {
        return getDoneTime();
    }

    @Override
    public LocalDateTime value11() {
        return getCtime();
    }

    @Override
    public LocalDateTime value12() {
        return getMtime();
    }

    @Override
    public String value13() {
        return getPipeOrganizer();
    }

    @Override
    public Integer value14() {
        return getPipeType();
    }

    @Override
    public ProcessActionPipeRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ProcessActionPipeRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ProcessActionPipeRecord value3(Long value) {
        setTaskId(value);
        return this;
    }

    @Override
    public ProcessActionPipeRecord value4(Long value) {
        setProcessId(value);
        return this;
    }

    @Override
    public ProcessActionPipeRecord value5(String value) {
        setContext(value);
        return this;
    }

    @Override
    public ProcessActionPipeRecord value6(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public ProcessActionPipeRecord value7(String value) {
        setHeadStageNo(value);
        return this;
    }

    @Override
    public ProcessActionPipeRecord value8(String value) {
        setTailStageNo(value);
        return this;
    }

    @Override
    public ProcessActionPipeRecord value9(LocalDateTime value) {
        setTriggerTime(value);
        return this;
    }

    @Override
    public ProcessActionPipeRecord value10(LocalDateTime value) {
        setDoneTime(value);
        return this;
    }

    @Override
    public ProcessActionPipeRecord value11(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public ProcessActionPipeRecord value12(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public ProcessActionPipeRecord value13(String value) {
        setPipeOrganizer(value);
        return this;
    }

    @Override
    public ProcessActionPipeRecord value14(Integer value) {
        setPipeType(value);
        return this;
    }

    @Override
    public ProcessActionPipeRecord values(Long value1, String value2, Long value3, Long value4, String value5, String value6, String value7, String value8, LocalDateTime value9, LocalDateTime value10, LocalDateTime value11, LocalDateTime value12, String value13, Integer value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProcessActionPipeRecord
     */
    public ProcessActionPipeRecord() {
        super(ProcessActionPipe.PROCESS_ACTION_PIPE);
    }

    /**
     * Create a detached, initialised ProcessActionPipeRecord
     */
    public ProcessActionPipeRecord(Long id, String name, Long taskId, Long processId, String context, String status, String headStageNo, String tailStageNo, LocalDateTime triggerTime, LocalDateTime doneTime, LocalDateTime ctime, LocalDateTime mtime, String pipeOrganizer, Integer pipeType) {
        super(ProcessActionPipe.PROCESS_ACTION_PIPE);

        set(0, id);
        set(1, name);
        set(2, taskId);
        set(3, processId);
        set(4, context);
        set(5, status);
        set(6, headStageNo);
        set(7, tailStageNo);
        set(8, triggerTime);
        set(9, doneTime);
        set(10, ctime);
        set(11, mtime);
        set(12, pipeOrganizer);
        set(13, pipeType);
    }
}
