/*
 * This file is generated by jOOQ.
 */
package com.ke.merchant.kernel.pipe.db.tables.records;


import com.ke.merchant.kernel.pipe.db.tables.ProcessAction;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * process_action
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProcessActionRecord extends UpdatableRecordImpl<ProcessActionRecord> {

    private static final long serialVersionUID = 1740562016;

    /**
     * Setter for <code>process_action.id</code>. pk
     */
    public ProcessActionRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>process_action.id</code>. pk
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>process_action.item_no</code>. 流水号
     */
    public ProcessActionRecord setItemNo(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>process_action.item_no</code>. 流水号
     */
    public String getItemNo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>process_action.pipe_id</code>. pipeId
     */
    public ProcessActionRecord setPipeId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>process_action.pipe_id</code>. pipeId
     */
    public Long getPipeId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>process_action.stage_no</code>. action 所属的阶段编号
     */
    public ProcessActionRecord setStageNo(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>process_action.stage_no</code>. action 所属的阶段编号
     */
    public String getStageNo() {
        return (String) get(3);
    }

    /**
     * Setter for <code>process_action.name</code>. action名称，在actionDef中定义
     */
    public ProcessActionRecord setName(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>process_action.name</code>. action名称，在actionDef中定义
     */
    public String getName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>process_action.context</code>. context
     */
    public ProcessActionRecord setContext(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>process_action.context</code>. context
     */
    public String getContext() {
        return (String) get(5);
    }

    /**
     * Setter for <code>process_action.input_script</code>. input 参数映射脚本
     */
    public ProcessActionRecord setInputScript(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>process_action.input_script</code>. input 参数映射脚本
     */
    public String getInputScript() {
        return (String) get(6);
    }

    /**
     * Setter for <code>process_action.clazz</code>. action的实现类，全类名
     */
    public ProcessActionRecord setClazz(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>process_action.clazz</code>. action的实现类，全类名
     */
    public String getClazz() {
        return (String) get(7);
    }

    /**
     * Setter for <code>process_action.param</code>. 请求信息
     */
    public ProcessActionRecord setParam(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>process_action.param</code>. 请求信息
     */
    public String getParam() {
        return (String) get(8);
    }

    /**
     * Setter for <code>process_action.result</code>. 响应信息
     */
    public ProcessActionRecord setResult(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>process_action.result</code>. 响应信息
     */
    public String getResult() {
        return (String) get(9);
    }

    /**
     * Setter for <code>process_action.biz_explain</code>. 业务信息说明
     */
    public ProcessActionRecord setBizExplain(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>process_action.biz_explain</code>. 业务信息说明
     */
    public String getBizExplain() {
        return (String) get(10);
    }

    /**
     * Setter for <code>process_action.exec_count</code>. 执行次数
     */
    public ProcessActionRecord setExecCount(Integer value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>process_action.exec_count</code>. 执行次数
     */
    public Integer getExecCount() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>process_action.err_msg</code>.
     */
    public ProcessActionRecord setErrMsg(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>process_action.err_msg</code>.
     */
    public String getErrMsg() {
        return (String) get(12);
    }

    /**
     * Setter for <code>process_action.tip</code>. tractId
     */
    public ProcessActionRecord setTip(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>process_action.tip</code>. tractId
     */
    public String getTip() {
        return (String) get(13);
    }

    /**
     * Setter for <code>process_action.task_id</code>. 任务id
     */
    public ProcessActionRecord setTaskId(Long value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>process_action.task_id</code>. 任务id
     */
    public Long getTaskId() {
        return (Long) get(14);
    }

    /**
     * Setter for <code>process_action.task_code</code>. 任务配置id
     */
    public ProcessActionRecord setTaskCode(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>process_action.task_code</code>. 任务配置id
     */
    public String getTaskCode() {
        return (String) get(15);
    }

    /**
     * Setter for <code>process_action.process_id</code>. 流程实例id
     */
    public ProcessActionRecord setProcessId(Long value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>process_action.process_id</code>. 流程实例id
     */
    public Long getProcessId() {
        return (Long) get(16);
    }

    /**
     * Setter for <code>process_action.status</code>. INIT_FAIL、INIT_SUCC、EXEC_FAIL、EXEC_SUCC、EXEC_SKIP
     */
    public ProcessActionRecord setStatus(String value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>process_action.status</code>. INIT_FAIL、INIT_SUCC、EXEC_FAIL、EXEC_SUCC、EXEC_SKIP
     */
    public String getStatus() {
        return (String) get(17);
    }

    /**
     * Setter for <code>process_action.exec_mode</code>. 执行方式: AUTO, MANUAL, SKIP
     */
    public ProcessActionRecord setExecMode(String value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>process_action.exec_mode</code>. 执行方式: AUTO, MANUAL, SKIP
     */
    public String getExecMode() {
        return (String) get(18);
    }

    /**
     * Setter for <code>process_action.ucid</code>. ucid
     */
    public ProcessActionRecord setUcid(String value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>process_action.ucid</code>. ucid
     */
    public String getUcid() {
        return (String) get(19);
    }

    /**
     * Setter for <code>process_action.admin_accounts</code>. 管理员用户名称, 逗号分隔
     */
    public ProcessActionRecord setAdminAccounts(String value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>process_action.admin_accounts</code>. 管理员用户名称, 逗号分隔
     */
    public String getAdminAccounts() {
        return (String) get(20);
    }

    /**
     * Setter for <code>process_action.done_time</code>. action 完成时间
     */
    public ProcessActionRecord setDoneTime(LocalDateTime value) {
        set(21, value);
        return this;
    }

    /**
     * Getter for <code>process_action.done_time</code>. action 完成时间
     */
    public LocalDateTime getDoneTime() {
        return (LocalDateTime) get(21);
    }

    /**
     * Setter for <code>process_action.ctime</code>. ctime
     */
    public ProcessActionRecord setCtime(LocalDateTime value) {
        set(22, value);
        return this;
    }

    /**
     * Getter for <code>process_action.ctime</code>. ctime
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(22);
    }

    /**
     * Setter for <code>process_action.mtime</code>. utime
     */
    public ProcessActionRecord setMtime(LocalDateTime value) {
        set(23, value);
        return this;
    }

    /**
     * Getter for <code>process_action.mtime</code>. utime
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(23);
    }

    /**
     * Setter for <code>process_action.deleted</code>. 已被删除
     */
    public ProcessActionRecord setDeleted(Integer value) {
        set(24, value);
        return this;
    }

    /**
     * Getter for <code>process_action.deleted</code>. 已被删除
     */
    public Integer getDeleted() {
        return (Integer) get(24);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProcessActionRecord
     */
    public ProcessActionRecord() {
        super(ProcessAction.PROCESS_ACTION);
    }

    /**
     * Create a detached, initialised ProcessActionRecord
     */
    public ProcessActionRecord(Long id, String itemNo, Long pipeId, String stageNo, String name, String context, String inputScript, String clazz, String param, String result, String bizExplain, Integer execCount, String errMsg, String tip, Long taskId, String taskCode, Long processId, String status, String execMode, String ucid, String adminAccounts, LocalDateTime doneTime, LocalDateTime ctime, LocalDateTime mtime, Integer deleted) {
        super(ProcessAction.PROCESS_ACTION);

        set(0, id);
        set(1, itemNo);
        set(2, pipeId);
        set(3, stageNo);
        set(4, name);
        set(5, context);
        set(6, inputScript);
        set(7, clazz);
        set(8, param);
        set(9, result);
        set(10, bizExplain);
        set(11, execCount);
        set(12, errMsg);
        set(13, tip);
        set(14, taskId);
        set(15, taskCode);
        set(16, processId);
        set(17, status);
        set(18, execMode);
        set(19, ucid);
        set(20, adminAccounts);
        set(21, doneTime);
        set(22, ctime);
        set(23, mtime);
        set(24, deleted);
    }
}
