/*
 * This file is generated by jOOQ.
 */
package com.ke.merchant.kernel.pipe.db.tables.records;


import com.ke.merchant.kernel.pipe.db.tables.ProcessActionOpLog;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Action 操作日志表
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProcessActionOpLogRecord extends UpdatableRecordImpl<ProcessActionOpLogRecord> implements Record8<Long, String, String, LocalDateTime, String, String, Long, LocalDateTime> {

    private static final long serialVersionUID = -332654963;

    /**
     * Setter for <code>process_action_op_log.id</code>. PK
     */
    public ProcessActionOpLogRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>process_action_op_log.id</code>. PK
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>process_action_op_log.resource_no</code>. resource_no
     */
    public ProcessActionOpLogRecord setResourceNo(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>process_action_op_log.resource_no</code>. resource_no
     */
    public String getResourceNo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>process_action_op_log.operation_type</code>. 操作类型
     */
    public ProcessActionOpLogRecord setOperationType(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>process_action_op_log.operation_type</code>. 操作类型
     */
    public String getOperationType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>process_action_op_log.operation_time</code>. 执行时间
     */
    public ProcessActionOpLogRecord setOperationTime(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>process_action_op_log.operation_time</code>. 执行时间
     */
    public LocalDateTime getOperationTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>process_action_op_log.address</code>. 执行机器地址
     */
    public ProcessActionOpLogRecord setAddress(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>process_action_op_log.address</code>. 执行机器地址
     */
    public String getAddress() {
        return (String) get(4);
    }

    /**
     * Setter for <code>process_action_op_log.username</code>. 用户名
     */
    public ProcessActionOpLogRecord setUsername(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>process_action_op_log.username</code>. 用户名
     */
    public String getUsername() {
        return (String) get(5);
    }

    /**
     * Setter for <code>process_action_op_log.ucid</code>. 用户ucid
     */
    public ProcessActionOpLogRecord setUcid(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>process_action_op_log.ucid</code>. 用户ucid
     */
    public Long getUcid() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>process_action_op_log.ctime</code>. ctime
     */
    public ProcessActionOpLogRecord setCtime(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>process_action_op_log.ctime</code>. ctime
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, String, String, LocalDateTime, String, String, Long, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, String, String, LocalDateTime, String, String, Long, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ProcessActionOpLog.PROCESS_ACTION_OP_LOG.ID;
    }

    @Override
    public Field<String> field2() {
        return ProcessActionOpLog.PROCESS_ACTION_OP_LOG.RESOURCE_NO;
    }

    @Override
    public Field<String> field3() {
        return ProcessActionOpLog.PROCESS_ACTION_OP_LOG.OPERATION_TYPE;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return ProcessActionOpLog.PROCESS_ACTION_OP_LOG.OPERATION_TIME;
    }

    @Override
    public Field<String> field5() {
        return ProcessActionOpLog.PROCESS_ACTION_OP_LOG.ADDRESS;
    }

    @Override
    public Field<String> field6() {
        return ProcessActionOpLog.PROCESS_ACTION_OP_LOG.USERNAME;
    }

    @Override
    public Field<Long> field7() {
        return ProcessActionOpLog.PROCESS_ACTION_OP_LOG.UCID;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return ProcessActionOpLog.PROCESS_ACTION_OP_LOG.CTIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getResourceNo();
    }

    @Override
    public String component3() {
        return getOperationType();
    }

    @Override
    public LocalDateTime component4() {
        return getOperationTime();
    }

    @Override
    public String component5() {
        return getAddress();
    }

    @Override
    public String component6() {
        return getUsername();
    }

    @Override
    public Long component7() {
        return getUcid();
    }

    @Override
    public LocalDateTime component8() {
        return getCtime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getResourceNo();
    }

    @Override
    public String value3() {
        return getOperationType();
    }

    @Override
    public LocalDateTime value4() {
        return getOperationTime();
    }

    @Override
    public String value5() {
        return getAddress();
    }

    @Override
    public String value6() {
        return getUsername();
    }

    @Override
    public Long value7() {
        return getUcid();
    }

    @Override
    public LocalDateTime value8() {
        return getCtime();
    }

    @Override
    public ProcessActionOpLogRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ProcessActionOpLogRecord value2(String value) {
        setResourceNo(value);
        return this;
    }

    @Override
    public ProcessActionOpLogRecord value3(String value) {
        setOperationType(value);
        return this;
    }

    @Override
    public ProcessActionOpLogRecord value4(LocalDateTime value) {
        setOperationTime(value);
        return this;
    }

    @Override
    public ProcessActionOpLogRecord value5(String value) {
        setAddress(value);
        return this;
    }

    @Override
    public ProcessActionOpLogRecord value6(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public ProcessActionOpLogRecord value7(Long value) {
        setUcid(value);
        return this;
    }

    @Override
    public ProcessActionOpLogRecord value8(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public ProcessActionOpLogRecord values(Long value1, String value2, String value3, LocalDateTime value4, String value5, String value6, Long value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProcessActionOpLogRecord
     */
    public ProcessActionOpLogRecord() {
        super(ProcessActionOpLog.PROCESS_ACTION_OP_LOG);
    }

    /**
     * Create a detached, initialised ProcessActionOpLogRecord
     */
    public ProcessActionOpLogRecord(Long id, String resourceNo, String operationType, LocalDateTime operationTime, String address, String username, Long ucid, LocalDateTime ctime) {
        super(ProcessActionOpLog.PROCESS_ACTION_OP_LOG);

        set(0, id);
        set(1, resourceNo);
        set(2, operationType);
        set(3, operationTime);
        set(4, address);
        set(5, username);
        set(6, ucid);
        set(7, ctime);
    }
}
