/*
 * This file is generated by jOOQ.
 */
package com.ke.merchant.kernel.pipe.db.tables.records;


import com.ke.merchant.kernel.pipe.db.tables.ProcessActionPipeDef;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Pipe 定义表
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProcessActionPipeDefRecord extends UpdatableRecordImpl<ProcessActionPipeDefRecord> implements Record9<Long, String, String, String, String, String, LocalDateTime, LocalDateTime, Integer> {

    private static final long serialVersionUID = 1101757195;

    /**
     * Setter for <code>process_action_pipe_def.id</code>. PK
     */
    public ProcessActionPipeDefRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>process_action_pipe_def.id</code>. PK
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>process_action_pipe_def.name</code>. name
     */
    public ProcessActionPipeDefRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>process_action_pipe_def.name</code>. name
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>process_action_pipe_def.code</code>. code
     */
    public ProcessActionPipeDefRecord setCode(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>process_action_pipe_def.code</code>. code
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>process_action_pipe_def.proc_code</code>. proc_code
     */
    public ProcessActionPipeDefRecord setProcCode(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>process_action_pipe_def.proc_code</code>. proc_code
     */
    public String getProcCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>process_action_pipe_def.task_code</code>. task_code
     */
    public ProcessActionPipeDefRecord setTaskCode(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>process_action_pipe_def.task_code</code>. task_code
     */
    public String getTaskCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>process_action_pipe_def.stage_def</code>. stage_def
     */
    public ProcessActionPipeDefRecord setStageDef(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>process_action_pipe_def.stage_def</code>. stage_def
     */
    public String getStageDef() {
        return (String) get(5);
    }

    /**
     * Setter for <code>process_action_pipe_def.ctime</code>. ctime
     */
    public ProcessActionPipeDefRecord setCtime(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>process_action_pipe_def.ctime</code>. ctime
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>process_action_pipe_def.mtime</code>. mtime
     */
    public ProcessActionPipeDefRecord setMtime(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>process_action_pipe_def.mtime</code>. mtime
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>process_action_pipe_def.deleted</code>. 逻辑删除
     */
    public ProcessActionPipeDefRecord setDeleted(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>process_action_pipe_def.deleted</code>. 逻辑删除
     */
    public Integer getDeleted() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, String, String, String, String, String, LocalDateTime, LocalDateTime, Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, String, String, String, String, String, LocalDateTime, LocalDateTime, Integer> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ProcessActionPipeDef.PROCESS_ACTION_PIPE_DEF.ID;
    }

    @Override
    public Field<String> field2() {
        return ProcessActionPipeDef.PROCESS_ACTION_PIPE_DEF.NAME;
    }

    @Override
    public Field<String> field3() {
        return ProcessActionPipeDef.PROCESS_ACTION_PIPE_DEF.CODE;
    }

    @Override
    public Field<String> field4() {
        return ProcessActionPipeDef.PROCESS_ACTION_PIPE_DEF.PROC_CODE;
    }

    @Override
    public Field<String> field5() {
        return ProcessActionPipeDef.PROCESS_ACTION_PIPE_DEF.TASK_CODE;
    }

    @Override
    public Field<String> field6() {
        return ProcessActionPipeDef.PROCESS_ACTION_PIPE_DEF.STAGE_DEF;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return ProcessActionPipeDef.PROCESS_ACTION_PIPE_DEF.CTIME;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return ProcessActionPipeDef.PROCESS_ACTION_PIPE_DEF.MTIME;
    }

    @Override
    public Field<Integer> field9() {
        return ProcessActionPipeDef.PROCESS_ACTION_PIPE_DEF.DELETED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getCode();
    }

    @Override
    public String component4() {
        return getProcCode();
    }

    @Override
    public String component5() {
        return getTaskCode();
    }

    @Override
    public String component6() {
        return getStageDef();
    }

    @Override
    public LocalDateTime component7() {
        return getCtime();
    }

    @Override
    public LocalDateTime component8() {
        return getMtime();
    }

    @Override
    public Integer component9() {
        return getDeleted();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getCode();
    }

    @Override
    public String value4() {
        return getProcCode();
    }

    @Override
    public String value5() {
        return getTaskCode();
    }

    @Override
    public String value6() {
        return getStageDef();
    }

    @Override
    public LocalDateTime value7() {
        return getCtime();
    }

    @Override
    public LocalDateTime value8() {
        return getMtime();
    }

    @Override
    public Integer value9() {
        return getDeleted();
    }

    @Override
    public ProcessActionPipeDefRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ProcessActionPipeDefRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ProcessActionPipeDefRecord value3(String value) {
        setCode(value);
        return this;
    }

    @Override
    public ProcessActionPipeDefRecord value4(String value) {
        setProcCode(value);
        return this;
    }

    @Override
    public ProcessActionPipeDefRecord value5(String value) {
        setTaskCode(value);
        return this;
    }

    @Override
    public ProcessActionPipeDefRecord value6(String value) {
        setStageDef(value);
        return this;
    }

    @Override
    public ProcessActionPipeDefRecord value7(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public ProcessActionPipeDefRecord value8(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public ProcessActionPipeDefRecord value9(Integer value) {
        setDeleted(value);
        return this;
    }

    @Override
    public ProcessActionPipeDefRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, LocalDateTime value7, LocalDateTime value8, Integer value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProcessActionPipeDefRecord
     */
    public ProcessActionPipeDefRecord() {
        super(ProcessActionPipeDef.PROCESS_ACTION_PIPE_DEF);
    }

    /**
     * Create a detached, initialised ProcessActionPipeDefRecord
     */
    public ProcessActionPipeDefRecord(Long id, String name, String code, String procCode, String taskCode, String stageDef, LocalDateTime ctime, LocalDateTime mtime, Integer deleted) {
        super(ProcessActionPipeDef.PROCESS_ACTION_PIPE_DEF);

        set(0, id);
        set(1, name);
        set(2, code);
        set(3, procCode);
        set(4, taskCode);
        set(5, stageDef);
        set(6, ctime);
        set(7, mtime);
        set(8, deleted);
    }
}
