/*
 * This file is generated by jOOQ.
 */
package com.merchant.pipe.db.tables.records;


import com.merchant.pipe.db.tables.ProcessActionGroup;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * actionGroup
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProcessActionGroupRecord extends UpdatableRecordImpl<ProcessActionGroupRecord> implements Record8<Long, String, Long, Long, String, LocalDateTime, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -1117329649;

    /**
     * Setter for <code>process_action_group.id</code>. pk
     */
    public ProcessActionGroupRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>process_action_group.id</code>. pk
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>process_action_group.name</code>. name
     */
    public ProcessActionGroupRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>process_action_group.name</code>. name
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>process_action_group.task_id</code>. taskId
     */
    public ProcessActionGroupRecord setTaskId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>process_action_group.task_id</code>. taskId
     */
    public Long getTaskId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>process_action_group.process_id</code>. processId
     */
    public ProcessActionGroupRecord setProcessId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>process_action_group.process_id</code>. processId
     */
    public Long getProcessId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>process_action_group.status</code>. status
     */
    public ProcessActionGroupRecord setStatus(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>process_action_group.status</code>. status
     */
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>process_action_group.trigger_time</code>. 定时触发时间
     */
    public ProcessActionGroupRecord setTriggerTime(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>process_action_group.trigger_time</code>. 定时触发时间
     */
    public LocalDateTime getTriggerTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>process_action_group.ctime</code>. ctime
     */
    public ProcessActionGroupRecord setCtime(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>process_action_group.ctime</code>. ctime
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>process_action_group.mtime</code>. mtime
     */
    public ProcessActionGroupRecord setMtime(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>process_action_group.mtime</code>. mtime
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, String, Long, Long, String, LocalDateTime, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, String, Long, Long, String, LocalDateTime, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ProcessActionGroup.PROCESS_ACTION_GROUP.ID;
    }

    @Override
    public Field<String> field2() {
        return ProcessActionGroup.PROCESS_ACTION_GROUP.NAME;
    }

    @Override
    public Field<Long> field3() {
        return ProcessActionGroup.PROCESS_ACTION_GROUP.TASK_ID;
    }

    @Override
    public Field<Long> field4() {
        return ProcessActionGroup.PROCESS_ACTION_GROUP.PROCESS_ID;
    }

    @Override
    public Field<String> field5() {
        return ProcessActionGroup.PROCESS_ACTION_GROUP.STATUS;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return ProcessActionGroup.PROCESS_ACTION_GROUP.TRIGGER_TIME;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return ProcessActionGroup.PROCESS_ACTION_GROUP.CTIME;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return ProcessActionGroup.PROCESS_ACTION_GROUP.MTIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Long component3() {
        return getTaskId();
    }

    @Override
    public Long component4() {
        return getProcessId();
    }

    @Override
    public String component5() {
        return getStatus();
    }

    @Override
    public LocalDateTime component6() {
        return getTriggerTime();
    }

    @Override
    public LocalDateTime component7() {
        return getCtime();
    }

    @Override
    public LocalDateTime component8() {
        return getMtime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Long value3() {
        return getTaskId();
    }

    @Override
    public Long value4() {
        return getProcessId();
    }

    @Override
    public String value5() {
        return getStatus();
    }

    @Override
    public LocalDateTime value6() {
        return getTriggerTime();
    }

    @Override
    public LocalDateTime value7() {
        return getCtime();
    }

    @Override
    public LocalDateTime value8() {
        return getMtime();
    }

    @Override
    public ProcessActionGroupRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ProcessActionGroupRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ProcessActionGroupRecord value3(Long value) {
        setTaskId(value);
        return this;
    }

    @Override
    public ProcessActionGroupRecord value4(Long value) {
        setProcessId(value);
        return this;
    }

    @Override
    public ProcessActionGroupRecord value5(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public ProcessActionGroupRecord value6(LocalDateTime value) {
        setTriggerTime(value);
        return this;
    }

    @Override
    public ProcessActionGroupRecord value7(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public ProcessActionGroupRecord value8(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public ProcessActionGroupRecord values(Long value1, String value2, Long value3, Long value4, String value5, LocalDateTime value6, LocalDateTime value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProcessActionGroupRecord
     */
    public ProcessActionGroupRecord() {
        super(ProcessActionGroup.PROCESS_ACTION_GROUP);
    }

    /**
     * Create a detached, initialised ProcessActionGroupRecord
     */
    public ProcessActionGroupRecord(Long id, String name, Long taskId, Long processId, String status, LocalDateTime triggerTime, LocalDateTime ctime, LocalDateTime mtime) {
        super(ProcessActionGroup.PROCESS_ACTION_GROUP);

        set(0, id);
        set(1, name);
        set(2, taskId);
        set(3, processId);
        set(4, status);
        set(5, triggerTime);
        set(6, ctime);
        set(7, mtime);
    }
}
